using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace FairyNext.PropGen
{
    /// <summary>
    /// 文本发射。三条纪律（承自 fork 的生成器与本仓库 tools/AbiGen）：
    ///  1. **确定性**：无日期、无路径、无环境变量；行序只由 PropId 决定；行尾固定 <c>\n</c>；
    ///  2. 生成物自带「不要手改 + 定义点在哪」的抬头；
    ///  3. 一条属性一段，段头注释写全 id/通道/存储——生成物要能被人读着 review。
    /// </summary>
    internal static class Emitter
    {
        private const string Nl = "\n";
        private const string BitEquals = "global::FairyNext.Numerics.BitEquals";

        internal static string EmitWriters(SymbolContext ctx, List<PropRow> rows)
        {
            var sb = new StringBuilder();
            Header(sb, "NodeTable 的每属性写口 + PropId 分派");
            sb.Append("namespace ").Append(ctx.NodeTable.ContainingNamespace.ToDisplayString()).Append(Nl);
            sb.Append("{").Append(Nl);
            sb.Append("    partial class ").Append(ctx.NodeTable.Name).Append(Nl);
            sb.Append("    {").Append(Nl);

            foreach (PropRow r in rows)
            {
                Section(sb, r, ctx);
                if (r.Store == "Unbacked") continue;

                sb.Append("        /// <summary>").Append(r.Name)
                  .Append(" 的 Mark 位集（通道归属 ∪ 下行伴随位）。</summary>").Append(Nl);
                sb.Append("        internal const Ch Marks").Append(r.Name).Append(" = ")
                  .Append(ctx.ChExpr(r.Marks)).Append(";").Append(Nl).Append(Nl);

                switch (r.Store)
                {
                    case "FloatColumn": FloatColumn(sb, r); break;
                    case "AlphaU8": AlphaU8(sb, r); break;
                    case "VisualBit": VisualBit(sb, r); break;
                }
            }

            Dispatch(sb, rows);

            sb.Append("    }").Append(Nl);
            sb.Append("}").Append(Nl);
            return sb.ToString();
        }

        internal static string EmitTable(string ns, string typeName, SymbolContext ctx, List<PropRow> rows)
        {
            var sb = new StringBuilder();
            Header(sb, "属性元表（诊断面与单测按此遍历全部属性）");
            sb.Append("namespace ").Append(ns).Append(Nl);
            sb.Append("{").Append(Nl);
            sb.Append("    static partial class ").Append(typeName).Append(Nl);
            sb.Append("    {").Append(Nl);
            sb.Append("        /// <summary>全部已启用的节点属性，按 PropId 升序。</summary>").Append(Nl);
            sb.Append("        public static readonly NodePropInfo[] All = new NodePropInfo[]").Append(Nl);
            sb.Append("        {").Append(Nl);
            foreach (PropRow r in rows)
            {
                sb.Append("            new NodePropInfo(").Append(r.Id).Append(", ")
                  .Append(Literal(r.Name)).Append(", ")
                  .Append(ctx.ChExpr(r.Channel)).Append(", ")
                  .Append(ctx.ChExpr(r.Marks)).Append(", ")
                  .Append("NodePropStore.").Append(r.Store).Append("),").Append(Nl);
            }
            sb.Append("        };").Append(Nl);
            sb.Append("    }").Append(Nl);
            sb.Append("}").Append(Nl);
            return sb.ToString();
        }

        private static void Header(StringBuilder sb, string what)
        {
            sb.Append("// <auto-generated>").Append(Nl);
            sb.Append("//   由 tools/PropGen（Roslyn 生成器）产出——不要手改。").Append(Nl);
            sb.Append("//   定义点：src/Core/NodeProps.cs 的 [NodeProp] 归属表 ⋈ src/Contracts/Abi.cs 的 PropId 单源。")
              .Append(Nl);
            sb.Append("//   本文件：").Append(what).Append("。").Append(Nl);
            sb.Append("//   通道归属封闭（架构不变量 1）在生成期执法：ABI 有 id 而归属表缺声明 = FNP001 编译错。")
              .Append(Nl);
            sb.Append("//   确定性：按 PropId 升序发射，声明顺序与文件位置不参与排序。").Append(Nl);
            sb.Append("// </auto-generated>").Append(Nl).Append(Nl);
            sb.Append("#nullable enable").Append(Nl).Append(Nl);
        }

        private static void Section(StringBuilder sb, PropRow r, SymbolContext ctx)
        {
            sb.Append("        // ── ").Append(r.Name)
              .Append(" · PropId=").Append(r.Id)
              .Append(" · 归属 ").Append(ctx.ChExpr(r.Channel))
              .Append(" · 存储 ").Append(r.Store);
            if (r.Store == "VisualBit") sb.Append("(").Append(r.Column).Append(":Visual.").Append(r.Bit).Append(")");
            else if (r.Store != "Unbacked") sb.Append("(").Append(r.Column).Append(")");
            sb.Append(Nl);
        }

        private static void FloatColumn(StringBuilder sb, PropRow r)
        {
            sb.Append("        /// <summary>写 ").Append(r.Name)
              .Append(" 列：等值切断（位等，NaN 视为相等）后写值，**不** Mark。true = 值真的变了。</summary>")
              .Append(Nl);
            sb.Append("        private bool Store").Append(r.Name).Append("(uint index, float value)").Append(Nl);
            sb.Append("        {").Append(Nl);
            sb.Append("            if (").Append(BitEquals).Append(".Eq(").Append(r.Column)
              .Append("[index], value)) return false;").Append(Nl);
            sb.Append("            ").Append(r.Column).Append("[index] = value;").Append(Nl);
            sb.Append("            return true;").Append(Nl);
            sb.Append("        }").Append(Nl).Append(Nl);
            Writer(sb, r, "float value", "Store" + r.Name + "(index, value)");
        }

        private static void AlphaU8(StringBuilder sb, PropRow r)
        {
            sb.Append("        /// <summary>写 ").Append(r.Name)
              .Append(" 的 u8 位段：**等值切断在存储值（u8）上做**——0.999 与 1.0 都是 255 ⇒ 不脏。</summary>")
              .Append(Nl);
            sb.Append("        private bool Store").Append(r.Name).Append("(uint index, float value)").Append(Nl);
            sb.Append("        {").Append(Nl);
            sb.Append("            byte a = ToU8(value);").Append(Nl);
            sb.Append("            uint v = ").Append(r.Column).Append("[index];").Append(Nl);
            sb.Append("            if (Visual.Alpha(v) == a) return false;").Append(Nl);
            sb.Append("            ").Append(r.Column).Append("[index] = Visual.WithAlpha(v, a);").Append(Nl);
            sb.Append("            return true;").Append(Nl);
            sb.Append("        }").Append(Nl).Append(Nl);
            Writer(sb, r, "float value", "Store" + r.Name + "(index, value)");
        }

        private static void VisualBit(StringBuilder sb, PropRow r)
        {
            sb.Append("        /// <summary>写 ").Append(r.Name)
              .Append(" 位：位值未变 ⇒ 不写、不 Mark。</summary>").Append(Nl);
            sb.Append("        private bool Store").Append(r.Name).Append("(uint index, bool on)").Append(Nl);
            sb.Append("        {").Append(Nl);
            sb.Append("            uint v = ").Append(r.Column).Append("[index];").Append(Nl);
            sb.Append("            if (((v & Visual.").Append(r.Bit).Append(") != 0) == on) return false;").Append(Nl);
            sb.Append("            ").Append(r.Column).Append("[index] = on ? v | Visual.").Append(r.Bit)
              .Append(" : v & ~Visual.").Append(r.Bit).Append(";").Append(Nl);
            sb.Append("            return true;").Append(Nl);
            sb.Append("        }").Append(Nl).Append(Nl);
            Writer(sb, r, "bool on", "Store" + r.Name + "(index, on)");
        }

        /// <summary>写口本体：写列成功才 Mark，<c>src</c> 原样传下去（失效理由由失效平面按来源派生）。</summary>
        private static void Writer(StringBuilder sb, PropRow r, string valueParam, string storeCall)
        {
            sb.Append("        /// <summary>写 ").Append(r.Name)
              .Append(" 并 Mark：等值切断 → 写列 → Mark(Marks").Append(r.Name)
              .Append(", src)。true = 已 Mark。</summary>").Append(Nl);
            sb.Append("        internal bool Write").Append(r.Name).Append("(uint index, ").Append(valueParam)
              .Append(", WriteSource src)").Append(Nl);
            sb.Append("        {").Append(Nl);
            sb.Append("            if (!").Append(storeCall).Append(") return false;").Append(Nl);
            sb.Append("            Mark(index, Marks").Append(r.Name).Append(", src);").Append(Nl);
            sb.Append("            return true;").Append(Nl);
            sb.Append("        }").Append(Nl).Append(Nl);
        }

        private static void Dispatch(StringBuilder sb, List<PropRow> rows)
        {
            sb.Append("        /// <summary>").Append(Nl);
            sb.Append("        /// PropId → 写口的**唯一**分派点（M1-06 手写 switch 的生成版）。").Append(Nl);
            sb.Append("        /// 调用方须已解引用并过相位写门（见 NodeTable.WriteAuthored）。").Append(Nl);
            sb.Append("        /// </summary>").Append(Nl);
            sb.Append("        /// <returns>值真的变了返回 true（= 已 Mark）。</returns>").Append(Nl);
            sb.Append("        internal bool WriteAuthoredDispatch(uint index, byte propId, float value, WriteSource src)")
              .Append(Nl);
            sb.Append("        {").Append(Nl);
            sb.Append("            switch (propId)").Append(Nl);
            sb.Append("            {").Append(Nl);
            foreach (PropRow r in rows)
            {
                sb.Append("                case ").Append(r.Id).Append(":");
                switch (r.Store)
                {
                    case "VisualBit":
                        sb.Append(" return Write").Append(r.Name).Append("(index, value != 0f, src);").Append(Nl);
                        break;
                    case "Unbacked":
                        // 静默不是选项：属性在 id 空间里存在、却写不进去，这件事必须响。
                        sb.Append(Nl).Append("                    UiAssert.That(false, ")
                          .Append(Literal("PropId=" + r.Id + " " + r.Name + " 已声明通道归属，但列尚未接入："
                              + r.Pending))
                          .Append(");").Append(Nl);
                        sb.Append("                    return false;").Append(Nl);
                        break;
                    default:
                        sb.Append(" return Write").Append(r.Name).Append("(index, value, src);").Append(Nl);
                        break;
                }
            }
            sb.Append("                default:").Append(Nl);
            sb.Append("                    UiAssert.That(false, \"WriteAuthored 收到未归属的 PropId=\" + propId")
              .Append(Nl);
            sb.Append("                        + \"（通道归属封闭：没有归属的属性不应存在 setter）\");").Append(Nl);
            sb.Append("                    return false;").Append(Nl);
            sb.Append("            }").Append(Nl);
            sb.Append("        }").Append(Nl);
        }

        private static string Literal(string s) =>
            Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(s, true);
    }
}
