// <auto-generated>
//   由 tools/AbiGen 生成——不要手改。定义点：src/Contracts/Abi.cs 的静态数据表。
//   改 ABI 的唯一流程：改 Abi.cs → dotnet run --project tools/AbiGen → 提交生成物。
//   生成器确定性：无日期、无环境变量、无绝对路径，仅按声明序输出。
//   本文件：mock 后端侧的同一组常量（独立副本）。
// </auto-generated>
//
// mock 后端不引用 FairyNext.Contracts：无 GPU 行为门的宿主必须能独立复述 ABI，
// 否则「两侧同意」退化为「同一个变量读了两次」。两份副本同源生成，漂移由字节比对门拦。

#nullable enable

namespace FairyNext.Backend.Mock;

/// <summary>
/// mock 后端的 ABI 常量副本。定义点是 src/Contracts/Abi.cs 的静态数据表。
/// </summary>
public static class AbiMock
{
    // ---- 标量 ----
    /// <summary>"FGB1" little-endian；头首 4 字节，不符即拒载</summary>
    public const uint FgbMagic = 0x31424746u;
    /// <summary>精确匹配，不匹配 = 结构性拒载（不降级）</summary>
    public const int FgbFormatVersion = 1;
    /// <summary>段 16B 对齐，定长记录 Cast 直读</summary>
    public const int FgbSectionAlignment = 16;
    /// <summary>bytes/实例；实例缓冲 stride</summary>
    public const int QuadInstanceSize = 80;
    /// <summary>实例数组对齐</summary>
    public const int QuadInstanceAlignment = 16;
    /// <summary>bytes/裁剪条目；条目 0 = None 哨兵</summary>
    public const int ClipEntrySize = 48;
    /// <summary>条目数组对齐</summary>
    public const int ClipEntryAlignment = 16;
    /// <summary>段纹理槽上限（route.texSlot 2bit 编码的定义域）</summary>
    public const int SegmentMaxTextures = 4;
    /// <summary>sortingOrder = paintOrder 下标 × 本值（派生，不独立维护）</summary>
    public const int PaintOrderStride = 16;
    /// <summary>实例布局变更必 bump——后端启动时比对</summary>
    public const int ShaderAbiVersion = 1;
    /// <summary>槽 0 = identity；溢出 → 该容器退 tier-2 重写 + 高水位</summary>
    public const int TransformSlotBudget = 32;
    /// <summary>按裁剪域数计；溢出 → 父窗口降级 + 警告</summary>
    public const int ClipEntryBudget = 16;
    /// <summary>GPU 缓冲回收的 pending 队列深度上限；超深 = 门不过</summary>
    public const int GpuFenceDepth = 4;
    /// <summary>64bit 脏掩码硬顶；超出 = 编译错误</summary>
    public const int MaxObservableProps = 64;
    /// <summary>P3 波次上限</summary>
    public const int CommandWaveLimit = 4;
    /// <summary>P5 兜底微排水轮次</summary>
    public const int LayoutMicroDrainLimit = 3;

    // ---- QuadInstance 字段（80B，16B 对齐） ----
    /// <summary>rect @0 +16：xy = 槽本地 min 角，zw = size</summary>
    public const int QuadRectOffset = 0;
    public const int QuadRectSize = 16;
    /// <summary>uvA @16 +16：corner(0,0)+(1,0) UV —— 按角归位，不用 min/max</summary>
    public const int QuadUvAOffset = 16;
    public const int QuadUvASize = 16;
    /// <summary>uvB @32 +16：corner(0,1)+(1,1) UV</summary>
    public const int QuadUvBOffset = 32;
    public const int QuadUvBSize = 16;
    /// <summary>color @48 +4：RGBA8 直通色（已乘 worldVisual α；未乘基色在 CPU 镜像 baseColor）</summary>
    public const int QuadColorOffset = 48;
    public const int QuadColorSize = 4;
    /// <summary>route @52 +4：位域见 RouteBits：slot | clipIndex | texSlot</summary>
    public const int QuadRouteOffset = 52;
    public const int QuadRouteSize = 4;
    /// <summary>flags @56 +4：位域见 QuadFlagBits</summary>
    public const int QuadFlagsOffset = 56;
    public const int QuadFlagsSize = 4;
    /// <summary>aux @60 +4：按 kind 复用：glyphIndex / 圆角 pack / 渐变句柄 / 径向填充参数（定点）</summary>
    public const int QuadAuxOffset = 60;
    public const int QuadAuxSize = 4;
    /// <summary>extra @64 +16：按 kind 复用：SDF 半径 / 曲线 em-bbox / 渐变端点 / 填充中心</summary>
    public const int QuadExtraOffset = 64;
    public const int QuadExtraSize = 16;

    // ---- ClipEntry 字段（48B） ----
    /// <summary>rect @0 +16：槽本地 xMin,yMin,xMax,yMax（outer）</summary>
    public const int ClipRectOffset = 0;
    public const int ClipRectSize = 16;
    /// <summary>soft @16 +8：软边梯度</summary>
    public const int ClipSoftOffset = 16;
    public const int ClipSoftSize = 8;
    /// <summary>radii @24 +16：四角半径 —— 圆角矩形 mask 进流，不走 stencil</summary>
    public const int ClipRadiiOffset = 24;
    public const int ClipRadiiSize = 16;
    /// <summary>slot @40 +4：绑定的 transform 槽下标</summary>
    public const int ClipSlotOffset = 40;
    public const int ClipSlotSize = 4;
    /// <summary>_pad @44 +4：对齐填充，写零（append-only：新字段从此处切）</summary>
    public const int ClipPadOffset = 44;
    public const int ClipPadSize = 4;

    // ---- route 位域（表覆盖全 32 位；保留位写零）----
    /// <summary>b0-7：transform 槽下标（0 = identity）</summary>
    public const int RouteSlotShift = 0;
    public const int RouteSlotBits = 8;
    public const uint RouteSlotMask = 0xFFu;
    /// <summary>b8-19：ClipEntry 下标（0 = None 哨兵，shader 零采样）</summary>
    public const int RouteClipIndexShift = 8;
    public const int RouteClipIndexBits = 12;
    public const uint RouteClipIndexMask = 0xFFFu;
    /// <summary>b20-21：段内纹理槽（定义域 = SegmentMaxTextures）</summary>
    public const int RouteTexSlotShift = 20;
    public const int RouteTexSlotBits = 2;
    public const uint RouteTexSlotMask = 0x3u;
    /// <summary>b22-31：保留，写零（append-only：新位域从此处切）</summary>
    public const int RouteReservedShift = 22;
    public const int RouteReservedBits = 10;
    public const uint RouteReservedMask = 0x3FFu;

    // ---- route 位域 取值（与 HLSL 侧同名宏逐字对应）----
    /// <summary>取 route.slot。</summary>
    public static uint RouteSlot(uint route) => (route >> RouteSlotShift) & RouteSlotMask;
    /// <summary>取 route.clipIndex。</summary>
    public static uint RouteClipIndex(uint route) => (route >> RouteClipIndexShift) & RouteClipIndexMask;
    /// <summary>取 route.texSlot。</summary>
    public static uint RouteTexSlot(uint route) => (route >> RouteTexSlotShift) & RouteTexSlotMask;
    /// <summary>取 route.reserved。</summary>
    public static uint RouteReserved(uint route) => (route >> RouteReservedShift) & RouteReservedMask;

    // ---- flags 位域（表覆盖全 32 位；保留位写零）----
    /// <summary>b0：字体图集只有 α 通道，采样后当灰度用</summary>
    public const int FlagsFontAlphaShift = 0;
    public const int FlagsFontAlphaBits = 1;
    public const uint FlagsFontAlphaMask = 0x1u;
    /// <summary>b1-2：b1 = SDF fill，b2 = SDF border</summary>
    public const int FlagsSdfShift = 1;
    public const int FlagsSdfBits = 2;
    public const uint FlagsSdfMask = 0x3u;
    /// <summary>b3：曲线字形（band 数据纹理求值；M1 只占位不实现）</summary>
    public const int FlagsCurveGlyphShift = 3;
    public const int FlagsCurveGlyphBits = 1;
    public const uint FlagsCurveGlyphMask = 0x1u;
    /// <summary>b4：worldVisual.grayed 落叶结果</summary>
    public const int FlagsGrayedShift = 4;
    public const int FlagsGrayedBits = 1;
    public const uint FlagsGrayedMask = 0x1u;
    /// <summary>b5：径向填充（技能 CD）走 shader 求值，参数在 aux/extra——不落孤岛</summary>
    public const int FlagsRadialFillShift = 5;
    public const int FlagsRadialFillBits = 1;
    public const uint FlagsRadialFillMask = 0x1u;
    /// <summary>b6-7：保留，写零</summary>
    public const int FlagsReservedLowShift = 6;
    public const int FlagsReservedLowBits = 2;
    public const uint FlagsReservedLowMask = 0x3u;
    /// <summary>b8-15：描边宽度（u8 定点）</summary>
    public const int FlagsBorderWShift = 8;
    public const int FlagsBorderWBits = 8;
    public const uint FlagsBorderWMask = 0xFFu;
    /// <summary>b16-17：texSlot 备用位（route 位域挤满时的迁移目的地）</summary>
    public const int FlagsTexSlotSpareShift = 16;
    public const int FlagsTexSlotSpareBits = 2;
    public const uint FlagsTexSlotSpareMask = 0x3u;
    /// <summary>b18-31：保留，写零</summary>
    public const int FlagsReservedHighShift = 18;
    public const int FlagsReservedHighBits = 14;
    public const uint FlagsReservedHighMask = 0x3FFFu;

    // ---- flags 位域 取值（与 HLSL 侧同名宏逐字对应）----
    /// <summary>取 flags.fontAlpha。</summary>
    public static uint FlagsFontAlpha(uint flags) => (flags >> FlagsFontAlphaShift) & FlagsFontAlphaMask;
    /// <summary>取 flags.sdf。</summary>
    public static uint FlagsSdf(uint flags) => (flags >> FlagsSdfShift) & FlagsSdfMask;
    /// <summary>取 flags.curveGlyph。</summary>
    public static uint FlagsCurveGlyph(uint flags) => (flags >> FlagsCurveGlyphShift) & FlagsCurveGlyphMask;
    /// <summary>取 flags.grayed。</summary>
    public static uint FlagsGrayed(uint flags) => (flags >> FlagsGrayedShift) & FlagsGrayedMask;
    /// <summary>取 flags.radialFill。</summary>
    public static uint FlagsRadialFill(uint flags) => (flags >> FlagsRadialFillShift) & FlagsRadialFillMask;
    /// <summary>取 flags.reservedLow。</summary>
    public static uint FlagsReservedLow(uint flags) => (flags >> FlagsReservedLowShift) & FlagsReservedLowMask;
    /// <summary>取 flags.borderW。</summary>
    public static uint FlagsBorderW(uint flags) => (flags >> FlagsBorderWShift) & FlagsBorderWMask;
    /// <summary>取 flags.texSlotSpare。</summary>
    public static uint FlagsTexSlotSpare(uint flags) => (flags >> FlagsTexSlotSpareShift) & FlagsTexSlotSpareMask;
    /// <summary>取 flags.reservedHigh。</summary>
    public static uint FlagsReservedHigh(uint flags) => (flags >> FlagsReservedHighShift) & FlagsReservedHighMask;

    // ---- PropId 分组（组间 gap 供 append-only 增长；id 0 = None 哨兵）----
    /// <summary>width/height/约束输入/autoSize —— Ch.Layout</summary>
    public const byte PropGroupLayoutFirst = 1;
    public const byte PropGroupLayoutLast = 63;
    /// <summary>alpha/tint/visible/grayed/touchable —— Ch.Color | Ch.Visible</summary>
    public const byte PropGroupVisualFirst = 64;
    public const byte PropGroupVisualLast = 95;
    /// <summary>文本串/字号/描边 —— Ch.Text</summary>
    public const byte PropGroupTextFirst = 96;
    public const byte PropGroupTextLast = 127;
    /// <summary>x/y/scale/rotation/skew/pixelSnap —— Ch.Transform</summary>
    public const byte PropGroupTransformFirst = 128;
    public const byte PropGroupTransformLast = 159;

    // ---- PropId（本期启用者；新 id 追加到所属分组末尾，永不重编号）----
    /// <summary>无属性哨兵。</summary>
    public const byte PropIdNone = 0;
    /// <summary>[Layout] authored 宽（布局输入；resolved 由 P5 独占写）</summary>
    public const byte PropIdWidth = 1;
    /// <summary>[Layout] authored 高</summary>
    public const byte PropIdHeight = 2;
    /// <summary>[Visual] 局部 α（worldVisual 按积级联）</summary>
    public const byte PropIdAlpha = 64;
    /// <summary>[Visual] 局部可见（worldVisual 按 AND 级联）</summary>
    public const byte PropIdVisible = 65;
    /// <summary>[Visual] 局部置灰（worldVisual 按 OR 级联）</summary>
    public const byte PropIdGrayed = 66;
    /// <summary>[Visual] tint 基色（未乘 α，Color 通道从基色重乘）</summary>
    public const byte PropIdColor = 67;
    /// <summary>[Visual] 局部可命中（worldVisual 按 AND 级联；事件平面 P0 读）</summary>
    public const byte PropIdTouchable = 68;
    /// <summary>[Text] 字符串表 id（STRT/LANG 视图叠加后取值）</summary>
    public const byte PropIdTextId = 96;
    /// <summary>[Text] 字号（逻辑单位；度量与栅格密度解耦）</summary>
    public const byte PropIdFontSize = 97;
    /// <summary>[Transform] authored 位置 x（节点原点在父空间）</summary>
    public const byte PropIdX = 128;
    /// <summary>[Transform] authored 位置 y（y 向下）</summary>
    public const byte PropIdY = 129;
    /// <summary>[Transform] 缩放 x（永远只有 authored 一份）</summary>
    public const byte PropIdScaleX = 130;
    /// <summary>[Transform] 缩放 y</summary>
    public const byte PropIdScaleY = 131;
    /// <summary>[Transform] 旋转（弧度，绕 pivot）</summary>
    public const byte PropIdRotation = 132;
    /// <summary>[Transform] 剪切角（弧度，水平剪切；fork 的双值 skewX/skewY 编译期归一）</summary>
    public const byte PropIdSkew = 133;
    /// <summary>[Transform] 像素对齐位（不级联；存 localVisual 位段，通道归 Transform）</summary>
    public const byte PropIdPixelSnap = 134;

    // ---- 编译期断言：字段首尾相接、末字段收口于结构尺寸、位域覆盖全 32 位 ----
    // 不成立即 1/0 → CS0020 编译错（L0 门：错误在跑起来之前死掉）。
    private const int AssertQuadRect = 1 / ((QuadRectOffset + QuadRectSize == QuadUvAOffset) ? 1 : 0);
    private const int AssertQuadUvA = 1 / ((QuadUvAOffset + QuadUvASize == QuadUvBOffset) ? 1 : 0);
    private const int AssertQuadUvB = 1 / ((QuadUvBOffset + QuadUvBSize == QuadColorOffset) ? 1 : 0);
    private const int AssertQuadColor = 1 / ((QuadColorOffset + QuadColorSize == QuadRouteOffset) ? 1 : 0);
    private const int AssertQuadRoute = 1 / ((QuadRouteOffset + QuadRouteSize == QuadFlagsOffset) ? 1 : 0);
    private const int AssertQuadFlags = 1 / ((QuadFlagsOffset + QuadFlagsSize == QuadAuxOffset) ? 1 : 0);
    private const int AssertQuadAux = 1 / ((QuadAuxOffset + QuadAuxSize == QuadExtraOffset) ? 1 : 0);
    private const int AssertQuadExtra = 1 / ((QuadExtraOffset + QuadExtraSize == QuadInstanceSize) ? 1 : 0);
    private const int AssertClipRect = 1 / ((ClipRectOffset + ClipRectSize == ClipSoftOffset) ? 1 : 0);
    private const int AssertClipSoft = 1 / ((ClipSoftOffset + ClipSoftSize == ClipRadiiOffset) ? 1 : 0);
    private const int AssertClipRadii = 1 / ((ClipRadiiOffset + ClipRadiiSize == ClipSlotOffset) ? 1 : 0);
    private const int AssertClipSlot = 1 / ((ClipSlotOffset + ClipSlotSize == ClipPadOffset) ? 1 : 0);
    private const int AssertClipPad = 1 / ((ClipPadOffset + ClipPadSize == ClipEntrySize) ? 1 : 0);
    private const int AssertRouteSlot = 1 / ((RouteSlotShift + RouteSlotBits == RouteClipIndexShift) ? 1 : 0);
    private const int AssertRouteClipIndex = 1 / ((RouteClipIndexShift + RouteClipIndexBits == RouteTexSlotShift) ? 1 : 0);
    private const int AssertRouteTexSlot = 1 / ((RouteTexSlotShift + RouteTexSlotBits == RouteReservedShift) ? 1 : 0);
    private const int AssertRouteReserved = 1 / ((RouteReservedShift + RouteReservedBits == 32) ? 1 : 0);
    private const int AssertFlagsFontAlpha = 1 / ((FlagsFontAlphaShift + FlagsFontAlphaBits == FlagsSdfShift) ? 1 : 0);
    private const int AssertFlagsSdf = 1 / ((FlagsSdfShift + FlagsSdfBits == FlagsCurveGlyphShift) ? 1 : 0);
    private const int AssertFlagsCurveGlyph = 1 / ((FlagsCurveGlyphShift + FlagsCurveGlyphBits == FlagsGrayedShift) ? 1 : 0);
    private const int AssertFlagsGrayed = 1 / ((FlagsGrayedShift + FlagsGrayedBits == FlagsRadialFillShift) ? 1 : 0);
    private const int AssertFlagsRadialFill = 1 / ((FlagsRadialFillShift + FlagsRadialFillBits == FlagsReservedLowShift) ? 1 : 0);
    private const int AssertFlagsReservedLow = 1 / ((FlagsReservedLowShift + FlagsReservedLowBits == FlagsBorderWShift) ? 1 : 0);
    private const int AssertFlagsBorderW = 1 / ((FlagsBorderWShift + FlagsBorderWBits == FlagsTexSlotSpareShift) ? 1 : 0);
    private const int AssertFlagsTexSlotSpare = 1 / ((FlagsTexSlotSpareShift + FlagsTexSlotSpareBits == FlagsReservedHighShift) ? 1 : 0);
    private const int AssertFlagsReservedHigh = 1 / ((FlagsReservedHighShift + FlagsReservedHighBits == 32) ? 1 : 0);

}
