// <auto-generated>
//   由 tools/AbiGen 生成——不要手改。定义点：src/Contracts/Abi.cs 的静态数据表。
//   改 ABI 的唯一流程：改 Abi.cs → dotnet run --project tools/AbiGen → 提交生成物。
//   生成器确定性：无日期、无环境变量、无绝对路径，仅按声明序输出。
// </auto-generated>
//
// 顶点流后端（Unity 段 MeshRenderer 与 WebGL2/GLES3 同一份四角展开）的 ABI include。
// 整数字段一律 UInt32 顶点属性：float32 顶点流会把 glyphIndex 圆到邻字形（fork 教训）。

#ifndef FAIRYNEXT_ABI_G_HLSL
#define FAIRYNEXT_ABI_G_HLSL

// ---- 标量 ----
#define FN_QUAD_INSTANCE_SIZE 80       // bytes/实例；实例缓冲 stride
#define FN_QUAD_INSTANCE_ALIGNMENT 16  // 实例数组对齐
#define FN_CLIP_ENTRY_SIZE 48          // bytes/裁剪条目；条目 0 = None 哨兵
#define FN_CLIP_ENTRY_ALIGNMENT 16     // 条目数组对齐
#define FN_SEGMENT_MAX_TEXTURES 4      // 段纹理槽上限（route.texSlot 2bit 编码的定义域）
#define FN_SHADER_ABI_VERSION 1        // 实例布局变更必 bump——后端启动时比对
#define FN_TRANSFORM_SLOT_BUDGET 32    // 槽 0 = identity；溢出 → 该容器退 tier-2 重写 + 高水位
#define FN_CLIP_ENTRY_BUDGET 16        // 按裁剪域数计；溢出 → 父窗口降级 + 警告

// ---- QuadInstance —— 唯一主路径的可见内容单位（80B）----
struct FnQuadInstance
{
    float4 rect;   // @ 0 +16  xy = 槽本地 min 角，zw = size
    float4 uvA;    // @16 +16  corner(0,0)+(1,0) UV —— 按角归位，不用 min/max
    float4 uvB;    // @32 +16  corner(0,1)+(1,1) UV
    uint   color;  // @48 + 4  RGBA8 直通色（已乘 worldVisual α；未乘基色在 CPU 镜像 baseColor）
    uint   route;  // @52 + 4  位域见 RouteBits：slot | clipIndex | texSlot
    uint   flags;  // @56 + 4  位域见 QuadFlagBits
    uint   aux;    // @60 + 4  按 kind 复用：glyphIndex / 圆角 pack / 渐变句柄 / 径向填充参数（定点）
    float4 extra;  // @64 +16  按 kind 复用：SDF 半径 / 曲线 em-bbox / 渐变端点 / 填充中心
};
#define FN_QUAD_RECT_OFFSET 0
#define FN_QUAD_RECT_SIZE 16
#define FN_QUAD_UV_A_OFFSET 16
#define FN_QUAD_UV_A_SIZE 16
#define FN_QUAD_UV_B_OFFSET 32
#define FN_QUAD_UV_B_SIZE 16
#define FN_QUAD_COLOR_OFFSET 48
#define FN_QUAD_COLOR_SIZE 4
#define FN_QUAD_ROUTE_OFFSET 52
#define FN_QUAD_ROUTE_SIZE 4
#define FN_QUAD_FLAGS_OFFSET 56
#define FN_QUAD_FLAGS_SIZE 4
#define FN_QUAD_AUX_OFFSET 60
#define FN_QUAD_AUX_SIZE 4
#define FN_QUAD_EXTRA_OFFSET 64
#define FN_QUAD_EXTRA_SIZE 16

// ---- ClipEntry —— 条目 0 = None 哨兵，shader 对其零采样（48B）----
struct FnClipEntry
{
    float4 rect;   // @ 0 +16  槽本地 xMin,yMin,xMax,yMax（outer）
    float2 soft;   // @16 + 8  软边梯度
    float4 radii;  // @24 +16  四角半径 —— 圆角矩形 mask 进流，不走 stencil
    uint   slot;   // @40 + 4  绑定的 transform 槽下标
    uint   _pad;   // @44 + 4  对齐填充，写零（append-only：新字段从此处切）
};
#define FN_CLIP_RECT_OFFSET 0
#define FN_CLIP_RECT_SIZE 16
#define FN_CLIP_SOFT_OFFSET 16
#define FN_CLIP_SOFT_SIZE 8
#define FN_CLIP_RADII_OFFSET 24
#define FN_CLIP_RADII_SIZE 16
#define FN_CLIP_SLOT_OFFSET 40
#define FN_CLIP_SLOT_SIZE 4
#define FN_CLIP_PAD_OFFSET 44
#define FN_CLIP_PAD_SIZE 4

// ---- route 位域（QuadInstance.route），表覆盖全 32 位；保留位写零 ----
#define FN_ROUTE_SLOT_SHIFT 0        // b0-7  transform 槽下标（0 = identity）
#define FN_ROUTE_SLOT_BITS 8
#define FN_ROUTE_SLOT_MASK 0xFFu
#define FN_ROUTE_SLOT(route) (((route) >> FN_ROUTE_SLOT_SHIFT) & FN_ROUTE_SLOT_MASK)
#define FN_ROUTE_CLIP_INDEX_SHIFT 8  // b8-19  ClipEntry 下标（0 = None 哨兵，shader 零采样）
#define FN_ROUTE_CLIP_INDEX_BITS 12
#define FN_ROUTE_CLIP_INDEX_MASK 0xFFFu
#define FN_ROUTE_CLIP_INDEX(route) (((route) >> FN_ROUTE_CLIP_INDEX_SHIFT) & FN_ROUTE_CLIP_INDEX_MASK)
#define FN_ROUTE_TEX_SLOT_SHIFT 20   // b20-21  段内纹理槽（定义域 = SegmentMaxTextures）
#define FN_ROUTE_TEX_SLOT_BITS 2
#define FN_ROUTE_TEX_SLOT_MASK 0x3u
#define FN_ROUTE_TEX_SLOT(route) (((route) >> FN_ROUTE_TEX_SLOT_SHIFT) & FN_ROUTE_TEX_SLOT_MASK)
#define FN_ROUTE_RESERVED_SHIFT 22   // b22-31  保留，写零（append-only：新位域从此处切）
#define FN_ROUTE_RESERVED_BITS 10
#define FN_ROUTE_RESERVED_MASK 0x3FFu
#define FN_ROUTE_RESERVED(route) (((route) >> FN_ROUTE_RESERVED_SHIFT) & FN_ROUTE_RESERVED_MASK)

// ---- flags 位域（QuadInstance.flags），表覆盖全 32 位；保留位写零 ----
#define FN_FLAGS_FONT_ALPHA_SHIFT 0       // b0  字体图集只有 α 通道，采样后当灰度用
#define FN_FLAGS_FONT_ALPHA_BITS 1
#define FN_FLAGS_FONT_ALPHA_MASK 0x1u
#define FN_FLAGS_FONT_ALPHA(flags) (((flags) >> FN_FLAGS_FONT_ALPHA_SHIFT) & FN_FLAGS_FONT_ALPHA_MASK)
#define FN_FLAGS_SDF_SHIFT 1              // b1-2  b1 = SDF fill，b2 = SDF border
#define FN_FLAGS_SDF_BITS 2
#define FN_FLAGS_SDF_MASK 0x3u
#define FN_FLAGS_SDF(flags) (((flags) >> FN_FLAGS_SDF_SHIFT) & FN_FLAGS_SDF_MASK)
#define FN_FLAGS_CURVE_GLYPH_SHIFT 3      // b3  曲线字形（band 数据纹理求值；M1 只占位不实现）
#define FN_FLAGS_CURVE_GLYPH_BITS 1
#define FN_FLAGS_CURVE_GLYPH_MASK 0x1u
#define FN_FLAGS_CURVE_GLYPH(flags) (((flags) >> FN_FLAGS_CURVE_GLYPH_SHIFT) & FN_FLAGS_CURVE_GLYPH_MASK)
#define FN_FLAGS_GRAYED_SHIFT 4           // b4  worldVisual.grayed 落叶结果
#define FN_FLAGS_GRAYED_BITS 1
#define FN_FLAGS_GRAYED_MASK 0x1u
#define FN_FLAGS_GRAYED(flags) (((flags) >> FN_FLAGS_GRAYED_SHIFT) & FN_FLAGS_GRAYED_MASK)
#define FN_FLAGS_RADIAL_FILL_SHIFT 5      // b5  径向填充（技能 CD）走 shader 求值，参数在 aux/extra——不落孤岛
#define FN_FLAGS_RADIAL_FILL_BITS 1
#define FN_FLAGS_RADIAL_FILL_MASK 0x1u
#define FN_FLAGS_RADIAL_FILL(flags) (((flags) >> FN_FLAGS_RADIAL_FILL_SHIFT) & FN_FLAGS_RADIAL_FILL_MASK)
#define FN_FLAGS_RESERVED_LOW_SHIFT 6     // b6-7  保留，写零
#define FN_FLAGS_RESERVED_LOW_BITS 2
#define FN_FLAGS_RESERVED_LOW_MASK 0x3u
#define FN_FLAGS_RESERVED_LOW(flags) (((flags) >> FN_FLAGS_RESERVED_LOW_SHIFT) & FN_FLAGS_RESERVED_LOW_MASK)
#define FN_FLAGS_BORDER_W_SHIFT 8         // b8-15  描边宽度（u8 定点）
#define FN_FLAGS_BORDER_W_BITS 8
#define FN_FLAGS_BORDER_W_MASK 0xFFu
#define FN_FLAGS_BORDER_W(flags) (((flags) >> FN_FLAGS_BORDER_W_SHIFT) & FN_FLAGS_BORDER_W_MASK)
#define FN_FLAGS_TEX_SLOT_SPARE_SHIFT 16  // b16-17  texSlot 备用位（route 位域挤满时的迁移目的地）
#define FN_FLAGS_TEX_SLOT_SPARE_BITS 2
#define FN_FLAGS_TEX_SLOT_SPARE_MASK 0x3u
#define FN_FLAGS_TEX_SLOT_SPARE(flags) (((flags) >> FN_FLAGS_TEX_SLOT_SPARE_SHIFT) & FN_FLAGS_TEX_SLOT_SPARE_MASK)
#define FN_FLAGS_RESERVED_HIGH_SHIFT 18   // b18-31  保留，写零
#define FN_FLAGS_RESERVED_HIGH_BITS 14
#define FN_FLAGS_RESERVED_HIGH_MASK 0x3FFFu
#define FN_FLAGS_RESERVED_HIGH(flags) (((flags) >> FN_FLAGS_RESERVED_HIGH_SHIFT) & FN_FLAGS_RESERVED_HIGH_MASK)

#endif // FAIRYNEXT_ABI_G_HLSL
