// <auto-generated>
//   由 tools/AbiGen 生成——不要手改。定义点：src/Contracts/Abi.cs 的静态数据表。
//   改 ABI 的唯一流程：改 Abi.cs → dotnet run --project tools/AbiGen → 提交生成物。
//   生成器确定性：无日期、无环境变量、无绝对路径，仅按声明序输出。
//   本文件：偏移/大小/位域常量 + 定义点交叉校验。
// </auto-generated>

#nullable enable

namespace FairyNext.Contracts;

/// <summary>
/// QuadInstance / ClipEntry 的字节布局、route/flags 位域、PropId 与预算常量。
/// 生成物；定义点是 <see cref="Abi"/> 的静态数据表。
/// </summary>
public static class AbiLayout
{
    // ---- 标量 ----
    /// <summary>"FGB1" little-endian；头首 4 字节，不符即拒载</summary>
    public const uint FgbMagic = 0x31424746u;
    /// <summary>精确匹配，不匹配 = 结构性拒载（不降级）</summary>
    public const int FgbFormatVersion = 1;
    /// <summary>段 16B 对齐，定长记录 Cast 直读</summary>
    public const int FgbSectionAlignment = 16;
    /// <summary>bytes/实例；实例缓冲 stride</summary>
    public const int QuadInstanceSize = 80;
    /// <summary>实例数组对齐</summary>
    public const int QuadInstanceAlignment = 16;
    /// <summary>bytes/裁剪条目；条目 0 = None 哨兵</summary>
    public const int ClipEntrySize = 48;
    /// <summary>条目数组对齐</summary>
    public const int ClipEntryAlignment = 16;
    /// <summary>段纹理槽上限（route.texSlot 2bit 编码的定义域）</summary>
    public const int SegmentMaxTextures = 4;
    /// <summary>sortingOrder = paintOrder 下标 × 本值（派生，不独立维护）</summary>
    public const int PaintOrderStride = 16;
    /// <summary>实例布局变更必 bump——后端启动时比对</summary>
    public const int ShaderAbiVersion = 1;
    /// <summary>槽 0 = identity；溢出 → 该容器退 tier-2 重写 + 高水位</summary>
    public const int TransformSlotBudget = 32;
    /// <summary>按裁剪域数计；溢出 → 父窗口降级 + 警告</summary>
    public const int ClipEntryBudget = 16;
    /// <summary>GPU 缓冲回收的 pending 队列深度上限；超深 = 门不过</summary>
    public const int GpuFenceDepth = 4;
    /// <summary>64bit 脏掩码硬顶；超出 = 编译错误</summary>
    public const int MaxObservableProps = 64;
    /// <summary>P3 波次上限</summary>
    public const int CommandWaveLimit = 4;
    /// <summary>P5 兜底微排水轮次</summary>
    public const int LayoutMicroDrainLimit = 3;
    /// <summary>FgbHeader 定长（16B 对齐；布局 = FgbHeaderFields）</summary>
    public const int FgbHeaderSize = 64;
    /// <summary>SectionDir 条目定长（布局 = FgbSectionDirFields）</summary>
    public const int FgbSectionDirEntrySize = 24;
    /// <summary>NODE 段列元素宽之和 = NodeTable 真值列 80B/节点</summary>
    public const int NodeBytesPerNode = 80;
    /// <summary>实例块头定长；控制器状态与编译期 scratch 从其后切</summary>
    public const int FgbInstanceHeaderBytes = 16;

    // ---- QuadInstance 字段（80B，16B 对齐） ----
    /// <summary>rect @0 +16：xy = 槽本地 min 角，zw = size</summary>
    public const int QuadRectOffset = 0;
    public const int QuadRectSize = 16;
    /// <summary>uvA @16 +16：corner(0,0)+(1,0) UV —— 按角归位，不用 min/max</summary>
    public const int QuadUvAOffset = 16;
    public const int QuadUvASize = 16;
    /// <summary>uvB @32 +16：corner(0,1)+(1,1) UV</summary>
    public const int QuadUvBOffset = 32;
    public const int QuadUvBSize = 16;
    /// <summary>color @48 +4：RGBA8 直通色（已乘 worldVisual α；未乘基色在 CPU 镜像 baseColor）</summary>
    public const int QuadColorOffset = 48;
    public const int QuadColorSize = 4;
    /// <summary>route @52 +4：位域见 RouteBits：slot | clipIndex | texSlot</summary>
    public const int QuadRouteOffset = 52;
    public const int QuadRouteSize = 4;
    /// <summary>flags @56 +4：位域见 QuadFlagBits</summary>
    public const int QuadFlagsOffset = 56;
    public const int QuadFlagsSize = 4;
    /// <summary>aux @60 +4：按 kind 复用：glyphIndex / 圆角 pack / 渐变句柄 / 径向填充参数（定点）</summary>
    public const int QuadAuxOffset = 60;
    public const int QuadAuxSize = 4;
    /// <summary>extra @64 +16：按 kind 复用：SDF 半径 / 曲线 em-bbox / 渐变端点 / 填充中心</summary>
    public const int QuadExtraOffset = 64;
    public const int QuadExtraSize = 16;

    // ---- ClipEntry 字段（48B） ----
    /// <summary>rect @0 +16：槽本地 xMin,yMin,xMax,yMax（outer）</summary>
    public const int ClipRectOffset = 0;
    public const int ClipRectSize = 16;
    /// <summary>soft @16 +8：软边梯度</summary>
    public const int ClipSoftOffset = 16;
    public const int ClipSoftSize = 8;
    /// <summary>radii @24 +16：四角半径 —— 圆角矩形 mask 进流，不走 stencil</summary>
    public const int ClipRadiiOffset = 24;
    public const int ClipRadiiSize = 16;
    /// <summary>slot @40 +4：绑定的 transform 槽下标</summary>
    public const int ClipSlotOffset = 40;
    public const int ClipSlotSize = 4;
    /// <summary>_pad @44 +4：对齐填充，写零（append-only：新字段从此处切）</summary>
    public const int ClipPadOffset = 44;
    public const int ClipPadSize = 4;

    // ---- route 位域（表覆盖全 32 位；保留位写零）----
    /// <summary>b0-7：transform 槽下标（0 = identity）</summary>
    public const int RouteSlotShift = 0;
    public const int RouteSlotBits = 8;
    public const uint RouteSlotMask = 0xFFu;
    /// <summary>b8-19：ClipEntry 下标（0 = None 哨兵，shader 零采样）</summary>
    public const int RouteClipIndexShift = 8;
    public const int RouteClipIndexBits = 12;
    public const uint RouteClipIndexMask = 0xFFFu;
    /// <summary>b20-21：段内纹理槽（定义域 = SegmentMaxTextures）</summary>
    public const int RouteTexSlotShift = 20;
    public const int RouteTexSlotBits = 2;
    public const uint RouteTexSlotMask = 0x3u;
    /// <summary>b22-31：保留，写零（append-only：新位域从此处切）</summary>
    public const int RouteReservedShift = 22;
    public const int RouteReservedBits = 10;
    public const uint RouteReservedMask = 0x3FFu;

    // ---- route 位域 取值（与 HLSL 侧同名宏逐字对应）----
    /// <summary>取 route.slot。</summary>
    public static uint RouteSlot(uint route) => (route >> RouteSlotShift) & RouteSlotMask;
    /// <summary>取 route.clipIndex。</summary>
    public static uint RouteClipIndex(uint route) => (route >> RouteClipIndexShift) & RouteClipIndexMask;
    /// <summary>取 route.texSlot。</summary>
    public static uint RouteTexSlot(uint route) => (route >> RouteTexSlotShift) & RouteTexSlotMask;
    /// <summary>取 route.reserved。</summary>
    public static uint RouteReserved(uint route) => (route >> RouteReservedShift) & RouteReservedMask;

    // ---- flags 位域（表覆盖全 32 位；保留位写零）----
    /// <summary>b0：字体图集只有 α 通道，采样后当灰度用</summary>
    public const int FlagsFontAlphaShift = 0;
    public const int FlagsFontAlphaBits = 1;
    public const uint FlagsFontAlphaMask = 0x1u;
    /// <summary>b1-2：b1 = SDF fill，b2 = SDF border</summary>
    public const int FlagsSdfShift = 1;
    public const int FlagsSdfBits = 2;
    public const uint FlagsSdfMask = 0x3u;
    /// <summary>b3：曲线字形（band 数据纹理求值；M1 只占位不实现）</summary>
    public const int FlagsCurveGlyphShift = 3;
    public const int FlagsCurveGlyphBits = 1;
    public const uint FlagsCurveGlyphMask = 0x1u;
    /// <summary>b4：worldVisual.grayed 落叶结果</summary>
    public const int FlagsGrayedShift = 4;
    public const int FlagsGrayedBits = 1;
    public const uint FlagsGrayedMask = 0x1u;
    /// <summary>b5：径向填充（技能 CD）走 shader 求值，参数在 aux/extra——不落孤岛</summary>
    public const int FlagsRadialFillShift = 5;
    public const int FlagsRadialFillBits = 1;
    public const uint FlagsRadialFillMask = 0x1u;
    /// <summary>b6-7：保留，写零</summary>
    public const int FlagsReservedLowShift = 6;
    public const int FlagsReservedLowBits = 2;
    public const uint FlagsReservedLowMask = 0x3u;
    /// <summary>b8-15：描边宽度（u8 定点）</summary>
    public const int FlagsBorderWShift = 8;
    public const int FlagsBorderWBits = 8;
    public const uint FlagsBorderWMask = 0xFFu;
    /// <summary>b16-17：texSlot 备用位（route 位域挤满时的迁移目的地）</summary>
    public const int FlagsTexSlotSpareShift = 16;
    public const int FlagsTexSlotSpareBits = 2;
    public const uint FlagsTexSlotSpareMask = 0x3u;
    /// <summary>b18-31：保留，写零</summary>
    public const int FlagsReservedHighShift = 18;
    public const int FlagsReservedHighBits = 14;
    public const uint FlagsReservedHighMask = 0x3FFFu;

    // ---- flags 位域 取值（与 HLSL 侧同名宏逐字对应）----
    /// <summary>取 flags.fontAlpha。</summary>
    public static uint FlagsFontAlpha(uint flags) => (flags >> FlagsFontAlphaShift) & FlagsFontAlphaMask;
    /// <summary>取 flags.sdf。</summary>
    public static uint FlagsSdf(uint flags) => (flags >> FlagsSdfShift) & FlagsSdfMask;
    /// <summary>取 flags.curveGlyph。</summary>
    public static uint FlagsCurveGlyph(uint flags) => (flags >> FlagsCurveGlyphShift) & FlagsCurveGlyphMask;
    /// <summary>取 flags.grayed。</summary>
    public static uint FlagsGrayed(uint flags) => (flags >> FlagsGrayedShift) & FlagsGrayedMask;
    /// <summary>取 flags.radialFill。</summary>
    public static uint FlagsRadialFill(uint flags) => (flags >> FlagsRadialFillShift) & FlagsRadialFillMask;
    /// <summary>取 flags.reservedLow。</summary>
    public static uint FlagsReservedLow(uint flags) => (flags >> FlagsReservedLowShift) & FlagsReservedLowMask;
    /// <summary>取 flags.borderW。</summary>
    public static uint FlagsBorderW(uint flags) => (flags >> FlagsBorderWShift) & FlagsBorderWMask;
    /// <summary>取 flags.texSlotSpare。</summary>
    public static uint FlagsTexSlotSpare(uint flags) => (flags >> FlagsTexSlotSpareShift) & FlagsTexSlotSpareMask;
    /// <summary>取 flags.reservedHigh。</summary>
    public static uint FlagsReservedHigh(uint flags) => (flags >> FlagsReservedHighShift) & FlagsReservedHighMask;

    // ---- aux 位域（仅 flags.radialFill 置位时有效）（表覆盖全 32 位；保留位写零）----
    /// <summary>b0-2：FillMethod：1 水平 2 垂直 3 Radial90 4 Radial180 5 Radial360（0 = 无填充）</summary>
    public const int RadialFillMethodShift = 0;
    public const int RadialFillMethodBits = 3;
    public const uint RadialFillMethodMask = 0x7u;
    /// <summary>b3-5：起点，按 method 解释（Origin90 / Origin180 / Origin360）</summary>
    public const int RadialFillOriginShift = 3;
    public const int RadialFillOriginBits = 3;
    public const uint RadialFillOriginMask = 0x7u;
    /// <summary>b6：1 = 顺时针（屏幕视觉；全链路 y 向下）</summary>
    public const int RadialFillClockwiseShift = 6;
    public const int RadialFillClockwiseBits = 1;
    public const uint RadialFillClockwiseMask = 0x1u;
    /// <summary>b7-15：保留，写零（append-only：新位域从此处切）</summary>
    public const int RadialFillReservedShift = 7;
    public const int RadialFillReservedBits = 9;
    public const uint RadialFillReservedMask = 0x1FFu;
    /// <summary>b16-31：完成比 u16 定点 = round(amount × 65535)</summary>
    public const int RadialFillAmountShift = 16;
    public const int RadialFillAmountBits = 16;
    public const uint RadialFillAmountMask = 0xFFFFu;

    // ---- aux 位域（仅 flags.radialFill 置位时有效） 取值（与 HLSL 侧同名宏逐字对应）----
    /// <summary>取 aux.method。</summary>
    public static uint RadialFillMethod(uint aux) => (aux >> RadialFillMethodShift) & RadialFillMethodMask;
    /// <summary>取 aux.origin。</summary>
    public static uint RadialFillOrigin(uint aux) => (aux >> RadialFillOriginShift) & RadialFillOriginMask;
    /// <summary>取 aux.clockwise。</summary>
    public static uint RadialFillClockwise(uint aux) => (aux >> RadialFillClockwiseShift) & RadialFillClockwiseMask;
    /// <summary>取 aux.reserved。</summary>
    public static uint RadialFillReserved(uint aux) => (aux >> RadialFillReservedShift) & RadialFillReservedMask;
    /// <summary>取 aux.amount。</summary>
    public static uint RadialFillAmount(uint aux) => (aux >> RadialFillAmountShift) & RadialFillAmountMask;

    // ---- PropId 分组（组间 gap 供 append-only 增长；id 0 = None 哨兵）----
    /// <summary>width/height/约束输入/autoSize —— Ch.Layout</summary>
    public const byte PropGroupLayoutFirst = 1;
    public const byte PropGroupLayoutLast = 63;
    /// <summary>alpha/tint/visible/grayed/touchable —— Ch.Color | Ch.Visible</summary>
    public const byte PropGroupVisualFirst = 64;
    public const byte PropGroupVisualLast = 95;
    /// <summary>文本串/字号/描边 —— Ch.Text</summary>
    public const byte PropGroupTextFirst = 96;
    public const byte PropGroupTextLast = 127;
    /// <summary>x/y/scale/rotation/skew/pixelSnap —— Ch.Transform</summary>
    public const byte PropGroupTransformFirst = 128;
    public const byte PropGroupTransformLast = 159;

    // ---- PropId（本期启用者；新 id 追加到所属分组末尾，永不重编号）----
    /// <summary>无属性哨兵。</summary>
    public const byte PropIdNone = 0;
    /// <summary>[Layout] authored 宽（布局输入；resolved 由 P5 独占写）</summary>
    public const byte PropIdWidth = 1;
    /// <summary>[Layout] authored 高</summary>
    public const byte PropIdHeight = 2;
    /// <summary>[Visual] 局部 α（worldVisual 按积级联）</summary>
    public const byte PropIdAlpha = 64;
    /// <summary>[Visual] 局部可见（worldVisual 按 AND 级联）</summary>
    public const byte PropIdVisible = 65;
    /// <summary>[Visual] 局部置灰（worldVisual 按 OR 级联）</summary>
    public const byte PropIdGrayed = 66;
    /// <summary>[Visual] tint 基色（未乘 α，Color 通道从基色重乘）</summary>
    public const byte PropIdColor = 67;
    /// <summary>[Visual] 局部可命中（worldVisual 按 AND 级联；事件平面 P0 读）</summary>
    public const byte PropIdTouchable = 68;
    /// <summary>[Text] 字符串表 id（STRT/LANG 视图叠加后取值）</summary>
    public const byte PropIdTextId = 96;
    /// <summary>[Text] 字号（逻辑单位；度量与栅格密度解耦）</summary>
    public const byte PropIdFontSize = 97;
    /// <summary>[Transform] authored 位置 x（节点原点在父空间）</summary>
    public const byte PropIdX = 128;
    /// <summary>[Transform] authored 位置 y（y 向下）</summary>
    public const byte PropIdY = 129;
    /// <summary>[Transform] 缩放 x（永远只有 authored 一份）</summary>
    public const byte PropIdScaleX = 130;
    /// <summary>[Transform] 缩放 y</summary>
    public const byte PropIdScaleY = 131;
    /// <summary>[Transform] 旋转（弧度，绕 pivot）</summary>
    public const byte PropIdRotation = 132;
    /// <summary>[Transform] 剪切角（弧度，水平剪切；fork 的双值 skewX/skewY 编译期归一）</summary>
    public const byte PropIdSkew = 133;
    /// <summary>[Transform] 像素对齐位（不级联；存 localVisual 位段，通道归 Transform）</summary>
    public const byte PropIdPixelSnap = 134;

    // ---- FgbHeader 字段（64B，16B 对齐；装载门 1/3 的读口） ----
    /// <summary>magic @0 +4：「FGB1」little-endian；不符拒载（装载门 1）</summary>
    public const int FgbHeaderMagicOffset = 0;
    public const int FgbHeaderMagicSize = 4;
    /// <summary>formatVersion @4 +4：精确匹配；不符 = 结构性拒载，不降级（装载门 1）</summary>
    public const int FgbHeaderFormatVersionOffset = 4;
    public const int FgbHeaderFormatVersionSize = 4;
    /// <summary>flags @8 +4：位域见 FgbFlagBits；未知位置位 = 拒载（头无段粒度前向兼容）</summary>
    public const int FgbHeaderFlagsOffset = 8;
    public const int FgbHeaderFlagsSize = 4;
    /// <summary>_reserved0 @12 +4：对齐填充，写零（使 u64 哈希三连 16B 对齐）</summary>
    public const int FgbHeaderReserved0Offset = 12;
    public const int FgbHeaderReserved0Size = 4;
    /// <summary>selfHash @16 +8：全 blob FNV-1a，本字段按零参与散列；发布包可信任跳过（装载门 3）</summary>
    public const int FgbHeaderSelfHashOffset = 16;
    public const int FgbHeaderSelfHashSize = 8;
    /// <summary>sourceHash @24 +8：源 .fui 描述符字节哈希（四维身份 1/4）</summary>
    public const int FgbHeaderSourceHashOffset = 24;
    public const int FgbHeaderSourceHashSize = 8;
    /// <summary>combinedRefHash @32 +8：链上全部被引用包 sourceHash，id 去重 ordinal 排序（四维身份 2/4）</summary>
    public const int FgbHeaderCombinedRefHashOffset = 32;
    public const int FgbHeaderCombinedRefHashSize = 8;
    /// <summary>scaleLevel @40 +2：内容缩放档（四维身份 3/4）</summary>
    public const int FgbHeaderScaleLevelOffset = 40;
    public const int FgbHeaderScaleLevelSize = 2;
    /// <summary>branchId @42 +2：branch 变体（四维身份 4/4）</summary>
    public const int FgbHeaderBranchIdOffset = 42;
    public const int FgbHeaderBranchIdSize = 2;
    /// <summary>sectionCount @44 +4：段目录条目数（目录紧随头部）</summary>
    public const int FgbHeaderSectionCountOffset = 44;
    public const int FgbHeaderSectionCountSize = 4;
    /// <summary>_reserved1 @48 +16：保留，写零（append-only：新字段从此处切）</summary>
    public const int FgbHeaderReserved1Offset = 48;
    public const int FgbHeaderReserved1Size = 16;

    // ---- SectionDir 条目字段（24B；装载门 2 的读口） ----
    /// <summary>fourcc @0 +4：段 id（FgbSectionIds）；未知 fourcc 整段跳过——前向兼容只保留在段粒度</summary>
    public const int FgbDirFourccOffset = 0;
    public const int FgbDirFourccSize = 4;
    /// <summary>_reserved @4 +4：保留，写零</summary>
    public const int FgbDirReservedOffset = 4;
    public const int FgbDirReservedSize = 4;
    /// <summary>offset @8 +8：段起点（blob 内字节偏移；必须 FgbSectionAlignment 对齐，装载门 2）</summary>
    public const int FgbDirOffsetOffset = 8;
    public const int FgbDirOffsetSize = 8;
    /// <summary>length @16 +8：段字节长（offset + length ≤ blob 长，装载门 2）</summary>
    public const int FgbDirLengthOffset = 16;
    public const int FgbDirLengthSize = 8;

    // ---- FgbHeader.flags 位域（表覆盖全 32 位；保留位写零）----
    /// <summary>b0：LE 断言位：写入器恒置 1；读到 0 = 大端产物，拒载</summary>
    public const int FgbFlagLittleEndianShift = 0;
    public const int FgbFlagLittleEndianBits = 1;
    public const uint FgbFlagLittleEndianMask = 0x1u;
    /// <summary>b1：压缩位：M1 不支持，置位即拒载（结构性）</summary>
    public const int FgbFlagCompressedShift = 1;
    public const int FgbFlagCompressedBits = 1;
    public const uint FgbFlagCompressedMask = 0x1u;
    /// <summary>b2-31：保留，写零；非零拒载</summary>
    public const int FgbFlagReservedShift = 2;
    public const int FgbFlagReservedBits = 30;
    public const uint FgbFlagReservedMask = 0x3FFFFFFFu;

    // ---- FgbHeader.flags 位域 取值（与 HLSL 侧同名宏逐字对应）----
    /// <summary>取 flags.littleEndian。</summary>
    public static uint FgbFlagLittleEndian(uint flags) => (flags >> FgbFlagLittleEndianShift) & FgbFlagLittleEndianMask;
    /// <summary>取 flags.compressed。</summary>
    public static uint FgbFlagCompressed(uint flags) => (flags >> FgbFlagCompressedShift) & FgbFlagCompressedMask;
    /// <summary>取 flags.reserved。</summary>
    public static uint FgbFlagReserved(uint flags) => (flags >> FgbFlagReservedShift) & FgbFlagReservedMask;

    // ---- FGB 段 fourcc（id append-only 永不复用；未知 fourcc 读取器整段跳过）----
    /// <summary>「STRT」：不可变字符串表</summary>
    public const uint FgbSectionStrt = 0x54525453u;
    /// <summary>「LANG」：每语言一段补丁（视图叠加，不改 STRT；同 fourcc 多段）</summary>
    public const uint FgbSectionLang = 0x474E414Cu;
    /// <summary>「COMP」：ComponentDef[]</summary>
    public const uint FgbSectionComp = 0x504D4F43u;
    /// <summary>「NODE」：NodeRecord SoA 分列子段（列序 = NodeColumns 表）</summary>
    public const uint FgbSectionNode = 0x45444F4Eu;
    /// <summary>「PLAN」：InstStep[] 后序扁平实例化计划</summary>
    public const uint FgbSectionPlan = 0x4E414C50u;
    /// <summary>「QUAD」：QuadInstance[]（80B shader ABI）</summary>
    public const uint FgbSectionQuad = 0x44415551u;
    /// <summary>「SEGS」：段表（冻结布局）</summary>
    public const uint FgbSectionSegs = 0x53474553u;
    /// <summary>「LEAF」：叶表</summary>
    public const uint FgbSectionLeaf = 0x4641454Cu;
    /// <summary>「CLIP」：ClipEntry 表</summary>
    public const uint FgbSectionClip = 0x50494C43u;
    /// <summary>「PTCH」：UvPatch[] 跨包 UV 装载期回填</summary>
    public const uint FgbSectionPtch = 0x48435450u;
    /// <summary>「CNST」：增量约束图（ConstraintOp + FanOut CSR）</summary>
    public const uint FgbSectionCnst = 0x54534E43u;
    /// <summary>「BIND」：StateProgram（归状态平面）</summary>
    public const uint FgbSectionBind = 0x444E4942u;
    /// <summary>「ANIM」：Timeline/Track/Key 冻结记录</summary>
    public const uint FgbSectionAnim = 0x4D494E41u;
    /// <summary>「SPRT」：sprite rects</summary>
    public const uint FgbSectionSprt = 0x54525053u;
    /// <summary>「TREF」：纹理/声音符号引用</summary>
    public const uint FgbSectionTref = 0x46455254u;
    /// <summary>「DEPS」：依赖包 { pkgId, expectedSourceHash }[]</summary>
    public const uint FgbSectionDeps = 0x53504544u;
    /// <summary>「HITT」：像素点击测试位图</summary>
    public const uint FgbSectionHitt = 0x54544948u;
    /// <summary>「BRCH」：branch 元数据</summary>
    public const uint FgbSectionBrch = 0x48435242u;
    /// <summary>「CONT」：内容条目表（contentRef 的目标；组件级降回运行时 Extract 的源）</summary>
    public const uint FgbSectionCont = 0x544E4F43u;
    /// <summary>「LOCL」：localId ⇄ 编辑器 id 映射</summary>
    public const uint FgbSectionLocl = 0x4C434F4Cu;

    // ---- NODE 段列序（列序 = NodeTable ABI；实例化 memcpy 的正确性锚）----
    // 列下标即段内顺序；手写第二份列序是缺陷——读写两侧都从本表走。
    /// <summary>NODE 段列数。</summary>
    public const int NodeColumnCount = 21;
    /// <summary>[0] +4（rebase：段内相对下标，实例化加基址回填）：父下标（0 = 无）</summary>
    public const int NodeColParent = 0;
    public const int NodeColParentSize = 4;
    public const bool NodeColParentRebase = true;
    /// <summary>[1] +4（rebase：段内相对下标，实例化加基址回填）：首子下标</summary>
    public const int NodeColFirstChild = 1;
    public const int NodeColFirstChildSize = 4;
    public const bool NodeColFirstChildRebase = true;
    /// <summary>[2] +4（rebase：段内相对下标，实例化加基址回填）：后兄下标（环形链）</summary>
    public const int NodeColNextSib = 2;
    public const int NodeColNextSibSize = 4;
    public const bool NodeColNextSibRebase = true;
    /// <summary>[3] +4（rebase：段内相对下标，实例化加基址回填）：前兄下标（环形链）</summary>
    public const int NodeColPrevSib = 3;
    public const int NodeColPrevSibSize = 4;
    public const bool NodeColPrevSibRebase = true;
    /// <summary>[4] +4（rebase：段内相对下标，实例化加基址回填）：所属组件实例节点下标</summary>
    public const int NodeColOwnerInst = 4;
    public const int NodeColOwnerInstSize = 4;
    public const bool NodeColOwnerInstRebase = true;
    /// <summary>[5] +2：模板内寻址 id（localId u16）</summary>
    public const int NodeColLocalId = 5;
    public const int NodeColLocalIdSize = 2;
    public const bool NodeColLocalIdRebase = false;
    /// <summary>[6] +2：节点类型 id</summary>
    public const int NodeColTypeId = 6;
    public const int NodeColTypeIdSize = 2;
    public const bool NodeColTypeIdRebase = false;
    /// <summary>[7] +4：authored 位置 x（节点原点在父空间）</summary>
    public const int NodeColPosX = 7;
    public const int NodeColPosXSize = 4;
    public const bool NodeColPosXRebase = false;
    /// <summary>[8] +4：authored 位置 y（y 向下）</summary>
    public const int NodeColPosY = 8;
    public const int NodeColPosYSize = 4;
    public const bool NodeColPosYRebase = false;
    /// <summary>[9] +4：authored 宽</summary>
    public const int NodeColWidth = 9;
    public const int NodeColWidthSize = 4;
    public const bool NodeColWidthRebase = false;
    /// <summary>[10] +4：authored 高</summary>
    public const int NodeColHeight = 10;
    public const int NodeColHeightSize = 4;
    public const bool NodeColHeightRebase = false;
    /// <summary>[11] +4：缩放 x</summary>
    public const int NodeColScaleX = 11;
    public const int NodeColScaleXSize = 4;
    public const bool NodeColScaleXRebase = false;
    /// <summary>[12] +4：缩放 y</summary>
    public const int NodeColScaleY = 12;
    public const int NodeColScaleYSize = 4;
    public const bool NodeColScaleYRebase = false;
    /// <summary>[13] +4：旋转（弧度，绕 pivot）</summary>
    public const int NodeColRotation = 13;
    public const int NodeColRotationSize = 4;
    public const bool NodeColRotationRebase = false;
    /// <summary>[14] +4：剪切角（弧度）</summary>
    public const int NodeColSkew = 14;
    public const int NodeColSkewSize = 4;
    public const bool NodeColSkewRebase = false;
    /// <summary>[15] +4：pivot x（比例）</summary>
    public const int NodeColPivotX = 15;
    public const int NodeColPivotXSize = 4;
    public const bool NodeColPivotXRebase = false;
    /// <summary>[16] +4：pivot y（比例）</summary>
    public const int NodeColPivotY = 16;
    public const int NodeColPivotYSize = 4;
    public const bool NodeColPivotYRebase = false;
    /// <summary>[17] +4：局部视觉位段（alpha/visible/grayed/touchable/pixelSnap 打包）</summary>
    public const int NodeColLocalVisual = 17;
    public const int NodeColLocalVisualSize = 4;
    public const bool NodeColLocalVisualRebase = false;
    /// <summary>[18] +4：内容侧表引用（不是节点下标，不回填）</summary>
    public const int NodeColContentRef = 18;
    public const int NodeColContentRefSize = 4;
    public const bool NodeColContentRefRebase = false;
    /// <summary>[19] +4：状态侧表引用</summary>
    public const int NodeColStateRef = 19;
    public const int NodeColStateRefSize = 4;
    public const bool NodeColStateRefRebase = false;
    /// <summary>[20] +4：resolved 几何槽引用（实例化批量分配后不再变，不变量 7）</summary>
    public const int NodeColResolvedRef = 20;
    public const int NodeColResolvedRefSize = 4;
    public const bool NodeColResolvedRefRebase = false;

    // ---- FgbComp 字段（96B）：COMP 记录（组件模板的全段区间） ----
    /// <summary>nameStr @0 +4：组件名在 STRT 的下标</summary>
    public const int FgbCompNameStrOffset = 0;
    public const int FgbCompNameStrSize = 4;
    /// <summary>nameHash @4 +4：组件名 FNV-1a 32（AssetServer.Resolve 的键）</summary>
    public const int FgbCompNameHashOffset = 4;
    public const int FgbCompNameHashSize = 4;
    /// <summary>nodeStart @8 +4：NODE 段内节点起点（列内元素下标）</summary>
    public const int FgbCompNodeStartOffset = 8;
    public const int FgbCompNodeStartSize = 4;
    /// <summary>nodeCount @12 +4：节点数（含局部 0 = 组件根）</summary>
    public const int FgbCompNodeCountOffset = 12;
    public const int FgbCompNodeCountSize = 4;
    /// <summary>quadStart @16 +4：QUAD 段内实例起点</summary>
    public const int FgbCompQuadStartOffset = 16;
    public const int FgbCompQuadStartSize = 4;
    /// <summary>quadCount @20 +4：实例数（含 slack 预留）</summary>
    public const int FgbCompQuadCountOffset = 20;
    public const int FgbCompQuadCountSize = 4;
    /// <summary>segStart @24 +4：SEGS 段内起点</summary>
    public const int FgbCompSegStartOffset = 24;
    public const int FgbCompSegStartSize = 4;
    /// <summary>segCount @28 +4：段数</summary>
    public const int FgbCompSegCountOffset = 28;
    public const int FgbCompSegCountSize = 4;
    /// <summary>leafStart @32 +4：LEAF 段内起点</summary>
    public const int FgbCompLeafStartOffset = 32;
    public const int FgbCompLeafStartSize = 4;
    /// <summary>leafCount @36 +4：叶数</summary>
    public const int FgbCompLeafCountOffset = 36;
    public const int FgbCompLeafCountSize = 4;
    /// <summary>clipStart @40 +4：CLIP 段内起点</summary>
    public const int FgbCompClipStartOffset = 40;
    public const int FgbCompClipStartSize = 4;
    /// <summary>clipCount @44 +4：ClipEntry 数（含条目 0 哨兵）</summary>
    public const int FgbCompClipCountOffset = 44;
    public const int FgbCompClipCountSize = 4;
    /// <summary>cnstOpStart @48 +4：CNST 算子起点（数组索引即拓扑序）</summary>
    public const int FgbCompCnstOpStartOffset = 48;
    public const int FgbCompCnstOpStartSize = 4;
    /// <summary>cnstOpCount @52 +4：算子数（0 = 本组件无关系）</summary>
    public const int FgbCompCnstOpCountOffset = 52;
    public const int FgbCompCnstOpCountSize = 4;
    /// <summary>cnstFanStart @56 +4：FanOut CSR 桶起点（桶数 = nodeCount，掩码同起点）</summary>
    public const int FgbCompCnstFanStartOffset = 56;
    public const int FgbCompCnstFanStartSize = 4;
    /// <summary>cnstIdxStart @60 +4：FanOut 算子下标池起点</summary>
    public const int FgbCompCnstIdxStartOffset = 60;
    public const int FgbCompCnstIdxStartSize = 4;
    /// <summary>cnstIdxCount @64 +4：下标池长度</summary>
    public const int FgbCompCnstIdxCountOffset = 64;
    public const int FgbCompCnstIdxCountSize = 4;
    /// <summary>localStart @68 +4：LOCL 段内起点</summary>
    public const int FgbCompLocalStartOffset = 68;
    public const int FgbCompLocalStartSize = 4;
    /// <summary>localCount @72 +4：localId 条目数（= nodeCount）</summary>
    public const int FgbCompLocalCountOffset = 72;
    public const int FgbCompLocalCountSize = 4;
    /// <summary>instanceBytes @76 +4：实例块字节（内存计划是承诺不是估计，运行期断言 15）</summary>
    public const int FgbCompInstanceBytesOffset = 76;
    public const int FgbCompInstanceBytesSize = 4;
    /// <summary>sourceWidth @80 +4：组件源宽</summary>
    public const int FgbCompSourceWidthOffset = 80;
    public const int FgbCompSourceWidthSize = 4;
    /// <summary>sourceHeight @84 +4：组件源高</summary>
    public const int FgbCompSourceHeightOffset = 84;
    public const int FgbCompSourceHeightSize = 4;
    /// <summary>ctrlCount @88 +2：控制器数（M1 恒 0——BIND 归 M2 状态层）</summary>
    public const int FgbCompCtrlCountOffset = 88;
    public const int FgbCompCtrlCountSize = 2;
    /// <summary>flags @90 +2：位域：bit0 有约束图 | bit1 有文本叶</summary>
    public const int FgbCompFlagsOffset = 90;
    public const int FgbCompFlagsSize = 2;
    /// <summary>_reserved @92 +4：保留，写零（append-only：新字段从此切）</summary>
    public const int FgbCompReservedOffset = 92;
    public const int FgbCompReservedSize = 4;

    /// <summary>COMP 记录（组件模板的全段区间） —— 记录定长。</summary>
    public const int FgbCompSize = 96;

    // ---- FgbCont 字段（80B）：CONT 记录（内容条目 = contentRef 的目标） ----
    /// <summary>kind @0 +2：0 = 无内容（哨兵 0 号记录）| 1 = 叶 | 2 = 孤岛（M1-23）</summary>
    public const int FgbContKindOffset = 0;
    public const int FgbContKindSize = 2;
    /// <summary>blend @2 +1：BlendClass（段键四类）</summary>
    public const int FgbContBlendOffset = 2;
    public const int FgbContBlendSize = 1;
    /// <summary>flags @3 +1：bit0 九宫格 | bit1 整图平铺 | bit2 开裁剪域 | bit3 文本叶</summary>
    public const int FgbContFlagsOffset = 3;
    public const int FgbContFlagsSize = 1;
    /// <summary>texId @4 +4：段键纹理 id（0 = 纯色；与 TREF 同源）</summary>
    public const int FgbContTexIdOffset = 4;
    public const int FgbContTexIdSize = 4;
    /// <summary>baseColor @8 +4：未乘 α 基色 RGBA8（颜色纯函数的定义域）</summary>
    public const int FgbContBaseColorOffset = 8;
    public const int FgbContBaseColorSize = 4;
    /// <summary>emitFlags @12 +4：发射器 flags</summary>
    public const int FgbContEmitFlagsOffset = 12;
    public const int FgbContEmitFlagsSize = 4;
    /// <summary>slackHint @16 +4：预留实例数下限（文本叶 = 有轮廓字形数 + 1，不依赖宽高）</summary>
    public const int FgbContSlackHintOffset = 16;
    public const int FgbContSlackHintSize = 4;
    /// <summary>tileGridIndice @20 +4：九宫平铺位掩码（M1 发射面拒发，有声计数）</summary>
    public const int FgbContTileGridIndiceOffset = 20;
    public const int FgbContTileGridIndiceSize = 4;
    /// <summary>textStr @24 +4：文本串在 STRT 的下标（0 = 非文本）</summary>
    public const int FgbContTextStrOffset = 24;
    public const int FgbContTextStrSize = 4;
    /// <summary>fillPack @28 +4：填充参数打包：method:8 | origin:8 | clockwise:1</summary>
    public const int FgbContFillPackOffset = 28;
    public const int FgbContFillPackSize = 4;
    /// <summary>uvX0 @32 +4：UV xMin</summary>
    public const int FgbContUvX0Offset = 32;
    public const int FgbContUvX0Size = 4;
    /// <summary>uvY0 @36 +4：UV yMin</summary>
    public const int FgbContUvY0Offset = 36;
    public const int FgbContUvY0Size = 4;
    /// <summary>uvX1 @40 +4：UV xMax</summary>
    public const int FgbContUvX1Offset = 40;
    public const int FgbContUvX1Size = 4;
    /// <summary>uvY1 @44 +4：UV yMax</summary>
    public const int FgbContUvY1Offset = 44;
    public const int FgbContUvY1Size = 4;
    /// <summary>srcW @48 +4：图元源宽（像素）</summary>
    public const int FgbContSourceWidthOffset = 48;
    public const int FgbContSourceWidthSize = 4;
    /// <summary>srcH @52 +4：图元源高（像素）</summary>
    public const int FgbContSourceHeightOffset = 52;
    public const int FgbContSourceHeightSize = 4;
    /// <summary>gridX @56 +4：九宫格 x（源像素）</summary>
    public const int FgbContGridXOffset = 56;
    public const int FgbContGridXSize = 4;
    /// <summary>gridY @60 +4：九宫格 y</summary>
    public const int FgbContGridYOffset = 60;
    public const int FgbContGridYSize = 4;
    /// <summary>gridW @64 +4：九宫格 w</summary>
    public const int FgbContGridWOffset = 64;
    public const int FgbContGridWSize = 4;
    /// <summary>gridH @68 +4：九宫格 h</summary>
    public const int FgbContGridHOffset = 68;
    public const int FgbContGridHSize = 4;
    /// <summary>fillAmount @72 +4：填充完成比 [0,1]</summary>
    public const int FgbContFillAmountOffset = 72;
    public const int FgbContFillAmountSize = 4;
    /// <summary>_reserved @76 +4：保留，写零</summary>
    public const int FgbContReservedOffset = 76;
    public const int FgbContReservedSize = 4;

    /// <summary>CONT 记录（内容条目 = contentRef 的目标） —— 记录定长。</summary>
    public const int FgbContSize = 80;

    // ---- FgbLocal 字段（16B）：LOCL 记录（localId ⇄ 编辑器 id） ----
    /// <summary>localId @0 +2：模板局部 id（0 = 组件根）</summary>
    public const int FgbLocalLocalIdOffset = 0;
    public const int FgbLocalLocalIdSize = 2;
    /// <summary>flags @2 +2：bit0 = GGroup 真节点化产生的组节点</summary>
    public const int FgbLocalFlagsOffset = 2;
    public const int FgbLocalFlagsSize = 2;
    /// <summary>editorIdStr @4 +4：编辑器 id 在 STRT 的下标（0 = 无）</summary>
    public const int FgbLocalEditorIdStrOffset = 4;
    public const int FgbLocalEditorIdStrSize = 4;
    /// <summary>nameStr @8 +4：编辑器 name 在 STRT 的下标（0 = 无）</summary>
    public const int FgbLocalNameStrOffset = 8;
    public const int FgbLocalNameStrSize = 4;
    /// <summary>editorIdHash @12 +4：编辑器 id 的 FNV-1a 32（陈旧可检测：arm 时比哈希链）</summary>
    public const int FgbLocalEditorIdHashOffset = 12;
    public const int FgbLocalEditorIdHashSize = 4;

    /// <summary>LOCL 记录（localId ⇄ 编辑器 id） —— 记录定长。</summary>
    public const int FgbLocalSize = 16;

    // ---- FgbLeaf 字段（40B）：LEAF 记录（叶在冻结流里的落位） ----
    /// <summary>localId @0 +2：叶节点的模板局部 id</summary>
    public const int FgbLeafLocalIdOffset = 0;
    public const int FgbLeafLocalIdSize = 2;
    /// <summary>texSlot @2 +2：叶在所属段内的纹理槽</summary>
    public const int FgbLeafTexSlotOffset = 2;
    public const int FgbLeafTexSlotSize = 2;
    /// <summary>quadStart @4 +4：首实例（**组件内相对**下标）</summary>
    public const int FgbLeafQuadStartOffset = 4;
    public const int FgbLeafQuadStartSize = 4;
    /// <summary>quadCount @8 +4：在用实例数</summary>
    public const int FgbLeafQuadCountOffset = 8;
    public const int FgbLeafQuadCountSize = 4;
    /// <summary>quadSlack @12 +4：预留实例数（写区间上界，≥ quadCount）</summary>
    public const int FgbLeafQuadSlackOffset = 12;
    public const int FgbLeafQuadSlackSize = 4;
    /// <summary>segment @16 +4：所属段（组件内相对）</summary>
    public const int FgbLeafSegmentOffset = 16;
    public const int FgbLeafSegmentSize = 4;
    /// <summary>run @20 +4：所属 run（组件内相对）</summary>
    public const int FgbLeafRunOffset = 20;
    public const int FgbLeafRunSize = 4;
    /// <summary>clipEntry @24 +4：裁剪条目（组件内相对；0 = 不裁剪）</summary>
    public const int FgbLeafClipEntryOffset = 24;
    public const int FgbLeafClipEntrySize = 4;
    /// <summary>slot @28 +4：transform 槽（0 = identity；实例化时 arm 重认领）</summary>
    public const int FgbLeafSlotOffset = 28;
    public const int FgbLeafSlotSize = 4;
    /// <summary>contentRef @32 +4：CONT 下标（canonical id：同内容必同 id）</summary>
    public const int FgbLeafContentRefOffset = 32;
    public const int FgbLeafContentRefSize = 4;
    /// <summary>emitFlags @36 +4：发射器 flags</summary>
    public const int FgbLeafEmitFlagsOffset = 36;
    public const int FgbLeafEmitFlagsSize = 4;

    /// <summary>LEAF 记录（叶在冻结流里的落位） —— 记录定长。</summary>
    public const int FgbLeafSize = 40;

    // ---- FgbSeg 字段（32B）：SEGS 记录（段键 + 实例区间） ----
    /// <summary>tex0 @0 +4：纹理槽 0</summary>
    public const int FgbSegTex0Offset = 0;
    public const int FgbSegTex0Size = 4;
    /// <summary>tex1 @4 +4：纹理槽 1</summary>
    public const int FgbSegTex1Offset = 4;
    public const int FgbSegTex1Size = 4;
    /// <summary>tex2 @8 +4：纹理槽 2</summary>
    public const int FgbSegTex2Offset = 8;
    public const int FgbSegTex2Size = 4;
    /// <summary>tex3 @12 +4：纹理槽 3</summary>
    public const int FgbSegTex3Offset = 12;
    public const int FgbSegTex3Size = 4;
    /// <summary>texCount @16 +1：在用纹理槽数（≤ SegmentMaxTextures）</summary>
    public const int FgbSegTexCountOffset = 16;
    public const int FgbSegTexCountSize = 1;
    /// <summary>blend @17 +1：BlendClass（进段键，不是栅栏）</summary>
    public const int FgbSegBlendOffset = 17;
    public const int FgbSegBlendSize = 1;
    /// <summary>_reserved @18 +2：保留，写零</summary>
    public const int FgbSegReservedOffset = 18;
    public const int FgbSegReservedSize = 2;
    /// <summary>quadStart @20 +4：首实例（组件内相对）</summary>
    public const int FgbSegQuadStartOffset = 20;
    public const int FgbSegQuadStartSize = 4;
    /// <summary>quadCount @24 +4：实例数</summary>
    public const int FgbSegQuadCountOffset = 24;
    public const int FgbSegQuadCountSize = 4;
    /// <summary>run @28 +4：所属 run（组件内相对）</summary>
    public const int FgbSegRunOffset = 28;
    public const int FgbSegRunSize = 4;

    /// <summary>SEGS 记录（段键 + 实例区间） —— 记录定长。</summary>
    public const int FgbSegSize = 32;

    // ---- FgbTexRef 字段（16B）：TREF 记录（纹理符号引用） ----
    /// <summary>pkgId @0 +8：包 id 字符串的 FNV-1a 64（本包引用 = 自身 id）</summary>
    public const int FgbTexRefPkgIdOffset = 0;
    public const int FgbTexRefPkgIdSize = 8;
    /// <summary>itemStr @8 +4：图集条目 id 在 STRT 的下标</summary>
    public const int FgbTexRefItemStrOffset = 8;
    public const int FgbTexRefItemStrSize = 4;
    /// <summary>kind @12 +2：0 = 纹理（声音/骨骼按 append-only 续编号）</summary>
    public const int FgbTexRefKindOffset = 12;
    public const int FgbTexRefKindSize = 2;
    /// <summary>texId @14 +2：段键纹理 id（包内分配序；QUAD 段键与本表同源）</summary>
    public const int FgbTexRefTexIdOffset = 14;
    public const int FgbTexRefTexIdSize = 2;

    /// <summary>TREF 记录（纹理符号引用） —— 记录定长。</summary>
    public const int FgbTexRefSize = 16;

    // ---- FgbStrtHeader 字段（16B）：STRT 段头 ----
    /// <summary>count @0 +4：条目数（下标 0 = 空串哨兵）</summary>
    public const int FgbStrtHeaderCountOffset = 0;
    public const int FgbStrtHeaderCountSize = 4;
    /// <summary>poolBytes @4 +4：UTF-8 池字节数</summary>
    public const int FgbStrtHeaderPoolBytesOffset = 4;
    public const int FgbStrtHeaderPoolBytesSize = 4;
    /// <summary>_reserved @8 +8：保留，写零（凑 16B 使条目数组自然对齐）</summary>
    public const int FgbStrtHeaderReservedOffset = 8;
    public const int FgbStrtHeaderReservedSize = 8;

    /// <summary>STRT 段头 —— 记录定长。</summary>
    public const int FgbStrtHeaderSize = 16;

    // ---- FgbStrtEntry 字段（8B）：STRT 条目 ----
    /// <summary>offset @0 +4：池内字节偏移</summary>
    public const int FgbStrtEntryOffsetOffset = 0;
    public const int FgbStrtEntryOffsetSize = 4;
    /// <summary>length @4 +4：字节长（UTF-8）</summary>
    public const int FgbStrtEntryLengthOffset = 4;
    public const int FgbStrtEntryLengthSize = 4;

    /// <summary>STRT 条目 —— 记录定长。</summary>
    public const int FgbStrtEntrySize = 8;

    // ---- FgbCnstHeader 字段（16B）：CNST 段头（四段数组总长） ----
    /// <summary>opCount @0 +4：ConstraintOp 总条数（8B/条）</summary>
    public const int FgbCnstHeaderOpCountOffset = 0;
    public const int FgbCnstHeaderOpCountSize = 4;
    /// <summary>fanCount @4 +4：FanOut 桶总数（4B/条；= 各组件 nodeCount 之和）</summary>
    public const int FgbCnstHeaderFanCountOffset = 4;
    public const int FgbCnstHeaderFanCountSize = 4;
    /// <summary>indexCount @8 +4：FanOut 算子下标池长度（2B/条）</summary>
    public const int FgbCnstHeaderIndexCountOffset = 8;
    public const int FgbCnstHeaderIndexCountSize = 4;
    /// <summary>maskCount @12 +4：布局归属掩码字节数（1B/节点；= fanCount）</summary>
    public const int FgbCnstHeaderMaskCountOffset = 12;
    public const int FgbCnstHeaderMaskCountSize = 4;

    /// <summary>CNST 段头（四段数组总长） —— 记录定长。</summary>
    public const int FgbCnstHeaderSize = 16;

    // ---- 编译期断言：字段首尾相接、末字段收口于结构尺寸、位域覆盖全 32 位 ----
    // 不成立即 1/0 → CS0020 编译错（L0 门：错误在跑起来之前死掉）。
    private const int AssertQuadRect = 1 / ((QuadRectOffset + QuadRectSize == QuadUvAOffset) ? 1 : 0);
    private const int AssertQuadUvA = 1 / ((QuadUvAOffset + QuadUvASize == QuadUvBOffset) ? 1 : 0);
    private const int AssertQuadUvB = 1 / ((QuadUvBOffset + QuadUvBSize == QuadColorOffset) ? 1 : 0);
    private const int AssertQuadColor = 1 / ((QuadColorOffset + QuadColorSize == QuadRouteOffset) ? 1 : 0);
    private const int AssertQuadRoute = 1 / ((QuadRouteOffset + QuadRouteSize == QuadFlagsOffset) ? 1 : 0);
    private const int AssertQuadFlags = 1 / ((QuadFlagsOffset + QuadFlagsSize == QuadAuxOffset) ? 1 : 0);
    private const int AssertQuadAux = 1 / ((QuadAuxOffset + QuadAuxSize == QuadExtraOffset) ? 1 : 0);
    private const int AssertQuadExtra = 1 / ((QuadExtraOffset + QuadExtraSize == QuadInstanceSize) ? 1 : 0);
    private const int AssertClipRect = 1 / ((ClipRectOffset + ClipRectSize == ClipSoftOffset) ? 1 : 0);
    private const int AssertClipSoft = 1 / ((ClipSoftOffset + ClipSoftSize == ClipRadiiOffset) ? 1 : 0);
    private const int AssertClipRadii = 1 / ((ClipRadiiOffset + ClipRadiiSize == ClipSlotOffset) ? 1 : 0);
    private const int AssertClipSlot = 1 / ((ClipSlotOffset + ClipSlotSize == ClipPadOffset) ? 1 : 0);
    private const int AssertClipPad = 1 / ((ClipPadOffset + ClipPadSize == ClipEntrySize) ? 1 : 0);
    private const int AssertRouteSlot = 1 / ((RouteSlotShift + RouteSlotBits == RouteClipIndexShift) ? 1 : 0);
    private const int AssertRouteClipIndex = 1 / ((RouteClipIndexShift + RouteClipIndexBits == RouteTexSlotShift) ? 1 : 0);
    private const int AssertRouteTexSlot = 1 / ((RouteTexSlotShift + RouteTexSlotBits == RouteReservedShift) ? 1 : 0);
    private const int AssertRouteReserved = 1 / ((RouteReservedShift + RouteReservedBits == 32) ? 1 : 0);
    private const int AssertFlagsFontAlpha = 1 / ((FlagsFontAlphaShift + FlagsFontAlphaBits == FlagsSdfShift) ? 1 : 0);
    private const int AssertFlagsSdf = 1 / ((FlagsSdfShift + FlagsSdfBits == FlagsCurveGlyphShift) ? 1 : 0);
    private const int AssertFlagsCurveGlyph = 1 / ((FlagsCurveGlyphShift + FlagsCurveGlyphBits == FlagsGrayedShift) ? 1 : 0);
    private const int AssertFlagsGrayed = 1 / ((FlagsGrayedShift + FlagsGrayedBits == FlagsRadialFillShift) ? 1 : 0);
    private const int AssertFlagsRadialFill = 1 / ((FlagsRadialFillShift + FlagsRadialFillBits == FlagsReservedLowShift) ? 1 : 0);
    private const int AssertFlagsReservedLow = 1 / ((FlagsReservedLowShift + FlagsReservedLowBits == FlagsBorderWShift) ? 1 : 0);
    private const int AssertFlagsBorderW = 1 / ((FlagsBorderWShift + FlagsBorderWBits == FlagsTexSlotSpareShift) ? 1 : 0);
    private const int AssertFlagsTexSlotSpare = 1 / ((FlagsTexSlotSpareShift + FlagsTexSlotSpareBits == FlagsReservedHighShift) ? 1 : 0);
    private const int AssertFlagsReservedHigh = 1 / ((FlagsReservedHighShift + FlagsReservedHighBits == 32) ? 1 : 0);
    private const int AssertRadialFillMethod = 1 / ((RadialFillMethodShift + RadialFillMethodBits == RadialFillOriginShift) ? 1 : 0);
    private const int AssertRadialFillOrigin = 1 / ((RadialFillOriginShift + RadialFillOriginBits == RadialFillClockwiseShift) ? 1 : 0);
    private const int AssertRadialFillClockwise = 1 / ((RadialFillClockwiseShift + RadialFillClockwiseBits == RadialFillReservedShift) ? 1 : 0);
    private const int AssertRadialFillReserved = 1 / ((RadialFillReservedShift + RadialFillReservedBits == RadialFillAmountShift) ? 1 : 0);
    private const int AssertRadialFillAmount = 1 / ((RadialFillAmountShift + RadialFillAmountBits == 32) ? 1 : 0);
    private const int AssertFgbHeaderMagic = 1 / ((FgbHeaderMagicOffset + FgbHeaderMagicSize == FgbHeaderFormatVersionOffset) ? 1 : 0);
    private const int AssertFgbHeaderFormatVersion = 1 / ((FgbHeaderFormatVersionOffset + FgbHeaderFormatVersionSize == FgbHeaderFlagsOffset) ? 1 : 0);
    private const int AssertFgbHeaderFlags = 1 / ((FgbHeaderFlagsOffset + FgbHeaderFlagsSize == FgbHeaderReserved0Offset) ? 1 : 0);
    private const int AssertFgbHeaderReserved0 = 1 / ((FgbHeaderReserved0Offset + FgbHeaderReserved0Size == FgbHeaderSelfHashOffset) ? 1 : 0);
    private const int AssertFgbHeaderSelfHash = 1 / ((FgbHeaderSelfHashOffset + FgbHeaderSelfHashSize == FgbHeaderSourceHashOffset) ? 1 : 0);
    private const int AssertFgbHeaderSourceHash = 1 / ((FgbHeaderSourceHashOffset + FgbHeaderSourceHashSize == FgbHeaderCombinedRefHashOffset) ? 1 : 0);
    private const int AssertFgbHeaderCombinedRefHash = 1 / ((FgbHeaderCombinedRefHashOffset + FgbHeaderCombinedRefHashSize == FgbHeaderScaleLevelOffset) ? 1 : 0);
    private const int AssertFgbHeaderScaleLevel = 1 / ((FgbHeaderScaleLevelOffset + FgbHeaderScaleLevelSize == FgbHeaderBranchIdOffset) ? 1 : 0);
    private const int AssertFgbHeaderBranchId = 1 / ((FgbHeaderBranchIdOffset + FgbHeaderBranchIdSize == FgbHeaderSectionCountOffset) ? 1 : 0);
    private const int AssertFgbHeaderSectionCount = 1 / ((FgbHeaderSectionCountOffset + FgbHeaderSectionCountSize == FgbHeaderReserved1Offset) ? 1 : 0);
    private const int AssertFgbHeaderReserved1 = 1 / ((FgbHeaderReserved1Offset + FgbHeaderReserved1Size == FgbHeaderSize) ? 1 : 0);
    private const int AssertFgbDirFourcc = 1 / ((FgbDirFourccOffset + FgbDirFourccSize == FgbDirReservedOffset) ? 1 : 0);
    private const int AssertFgbDirReserved = 1 / ((FgbDirReservedOffset + FgbDirReservedSize == FgbDirOffsetOffset) ? 1 : 0);
    private const int AssertFgbDirOffset = 1 / ((FgbDirOffsetOffset + FgbDirOffsetSize == FgbDirLengthOffset) ? 1 : 0);
    private const int AssertFgbDirLength = 1 / ((FgbDirLengthOffset + FgbDirLengthSize == FgbSectionDirEntrySize) ? 1 : 0);
    private const int AssertFgbFlagLittleEndian = 1 / ((FgbFlagLittleEndianShift + FgbFlagLittleEndianBits == FgbFlagCompressedShift) ? 1 : 0);
    private const int AssertFgbFlagCompressed = 1 / ((FgbFlagCompressedShift + FgbFlagCompressedBits == FgbFlagReservedShift) ? 1 : 0);
    private const int AssertFgbFlagReserved = 1 / ((FgbFlagReservedShift + FgbFlagReservedBits == 32) ? 1 : 0);
    private const int AssertNodeColumnBytes = 1 / ((NodeColParentSize + NodeColFirstChildSize + NodeColNextSibSize + NodeColPrevSibSize + NodeColOwnerInstSize + NodeColLocalIdSize + NodeColTypeIdSize + NodeColPosXSize + NodeColPosYSize + NodeColWidthSize + NodeColHeightSize + NodeColScaleXSize + NodeColScaleYSize + NodeColRotationSize + NodeColSkewSize + NodeColPivotXSize + NodeColPivotYSize + NodeColLocalVisualSize + NodeColContentRefSize + NodeColStateRefSize + NodeColResolvedRefSize == NodeBytesPerNode) ? 1 : 0);
    private const int AssertFgbCompNameStr = 1 / ((FgbCompNameStrOffset + FgbCompNameStrSize == FgbCompNameHashOffset) ? 1 : 0);
    private const int AssertFgbCompNameHash = 1 / ((FgbCompNameHashOffset + FgbCompNameHashSize == FgbCompNodeStartOffset) ? 1 : 0);
    private const int AssertFgbCompNodeStart = 1 / ((FgbCompNodeStartOffset + FgbCompNodeStartSize == FgbCompNodeCountOffset) ? 1 : 0);
    private const int AssertFgbCompNodeCount = 1 / ((FgbCompNodeCountOffset + FgbCompNodeCountSize == FgbCompQuadStartOffset) ? 1 : 0);
    private const int AssertFgbCompQuadStart = 1 / ((FgbCompQuadStartOffset + FgbCompQuadStartSize == FgbCompQuadCountOffset) ? 1 : 0);
    private const int AssertFgbCompQuadCount = 1 / ((FgbCompQuadCountOffset + FgbCompQuadCountSize == FgbCompSegStartOffset) ? 1 : 0);
    private const int AssertFgbCompSegStart = 1 / ((FgbCompSegStartOffset + FgbCompSegStartSize == FgbCompSegCountOffset) ? 1 : 0);
    private const int AssertFgbCompSegCount = 1 / ((FgbCompSegCountOffset + FgbCompSegCountSize == FgbCompLeafStartOffset) ? 1 : 0);
    private const int AssertFgbCompLeafStart = 1 / ((FgbCompLeafStartOffset + FgbCompLeafStartSize == FgbCompLeafCountOffset) ? 1 : 0);
    private const int AssertFgbCompLeafCount = 1 / ((FgbCompLeafCountOffset + FgbCompLeafCountSize == FgbCompClipStartOffset) ? 1 : 0);
    private const int AssertFgbCompClipStart = 1 / ((FgbCompClipStartOffset + FgbCompClipStartSize == FgbCompClipCountOffset) ? 1 : 0);
    private const int AssertFgbCompClipCount = 1 / ((FgbCompClipCountOffset + FgbCompClipCountSize == FgbCompCnstOpStartOffset) ? 1 : 0);
    private const int AssertFgbCompCnstOpStart = 1 / ((FgbCompCnstOpStartOffset + FgbCompCnstOpStartSize == FgbCompCnstOpCountOffset) ? 1 : 0);
    private const int AssertFgbCompCnstOpCount = 1 / ((FgbCompCnstOpCountOffset + FgbCompCnstOpCountSize == FgbCompCnstFanStartOffset) ? 1 : 0);
    private const int AssertFgbCompCnstFanStart = 1 / ((FgbCompCnstFanStartOffset + FgbCompCnstFanStartSize == FgbCompCnstIdxStartOffset) ? 1 : 0);
    private const int AssertFgbCompCnstIdxStart = 1 / ((FgbCompCnstIdxStartOffset + FgbCompCnstIdxStartSize == FgbCompCnstIdxCountOffset) ? 1 : 0);
    private const int AssertFgbCompCnstIdxCount = 1 / ((FgbCompCnstIdxCountOffset + FgbCompCnstIdxCountSize == FgbCompLocalStartOffset) ? 1 : 0);
    private const int AssertFgbCompLocalStart = 1 / ((FgbCompLocalStartOffset + FgbCompLocalStartSize == FgbCompLocalCountOffset) ? 1 : 0);
    private const int AssertFgbCompLocalCount = 1 / ((FgbCompLocalCountOffset + FgbCompLocalCountSize == FgbCompInstanceBytesOffset) ? 1 : 0);
    private const int AssertFgbCompInstanceBytes = 1 / ((FgbCompInstanceBytesOffset + FgbCompInstanceBytesSize == FgbCompSourceWidthOffset) ? 1 : 0);
    private const int AssertFgbCompSourceWidth = 1 / ((FgbCompSourceWidthOffset + FgbCompSourceWidthSize == FgbCompSourceHeightOffset) ? 1 : 0);
    private const int AssertFgbCompSourceHeight = 1 / ((FgbCompSourceHeightOffset + FgbCompSourceHeightSize == FgbCompCtrlCountOffset) ? 1 : 0);
    private const int AssertFgbCompCtrlCount = 1 / ((FgbCompCtrlCountOffset + FgbCompCtrlCountSize == FgbCompFlagsOffset) ? 1 : 0);
    private const int AssertFgbCompFlags = 1 / ((FgbCompFlagsOffset + FgbCompFlagsSize == FgbCompReservedOffset) ? 1 : 0);
    private const int AssertFgbCompReserved = 1 / ((FgbCompReservedOffset + FgbCompReservedSize == FgbCompSize) ? 1 : 0);
    private const int AssertFgbContKind = 1 / ((FgbContKindOffset + FgbContKindSize == FgbContBlendOffset) ? 1 : 0);
    private const int AssertFgbContBlend = 1 / ((FgbContBlendOffset + FgbContBlendSize == FgbContFlagsOffset) ? 1 : 0);
    private const int AssertFgbContFlags = 1 / ((FgbContFlagsOffset + FgbContFlagsSize == FgbContTexIdOffset) ? 1 : 0);
    private const int AssertFgbContTexId = 1 / ((FgbContTexIdOffset + FgbContTexIdSize == FgbContBaseColorOffset) ? 1 : 0);
    private const int AssertFgbContBaseColor = 1 / ((FgbContBaseColorOffset + FgbContBaseColorSize == FgbContEmitFlagsOffset) ? 1 : 0);
    private const int AssertFgbContEmitFlags = 1 / ((FgbContEmitFlagsOffset + FgbContEmitFlagsSize == FgbContSlackHintOffset) ? 1 : 0);
    private const int AssertFgbContSlackHint = 1 / ((FgbContSlackHintOffset + FgbContSlackHintSize == FgbContTileGridIndiceOffset) ? 1 : 0);
    private const int AssertFgbContTileGridIndice = 1 / ((FgbContTileGridIndiceOffset + FgbContTileGridIndiceSize == FgbContTextStrOffset) ? 1 : 0);
    private const int AssertFgbContTextStr = 1 / ((FgbContTextStrOffset + FgbContTextStrSize == FgbContFillPackOffset) ? 1 : 0);
    private const int AssertFgbContFillPack = 1 / ((FgbContFillPackOffset + FgbContFillPackSize == FgbContUvX0Offset) ? 1 : 0);
    private const int AssertFgbContUvX0 = 1 / ((FgbContUvX0Offset + FgbContUvX0Size == FgbContUvY0Offset) ? 1 : 0);
    private const int AssertFgbContUvY0 = 1 / ((FgbContUvY0Offset + FgbContUvY0Size == FgbContUvX1Offset) ? 1 : 0);
    private const int AssertFgbContUvX1 = 1 / ((FgbContUvX1Offset + FgbContUvX1Size == FgbContUvY1Offset) ? 1 : 0);
    private const int AssertFgbContUvY1 = 1 / ((FgbContUvY1Offset + FgbContUvY1Size == FgbContSourceWidthOffset) ? 1 : 0);
    private const int AssertFgbContSourceWidth = 1 / ((FgbContSourceWidthOffset + FgbContSourceWidthSize == FgbContSourceHeightOffset) ? 1 : 0);
    private const int AssertFgbContSourceHeight = 1 / ((FgbContSourceHeightOffset + FgbContSourceHeightSize == FgbContGridXOffset) ? 1 : 0);
    private const int AssertFgbContGridX = 1 / ((FgbContGridXOffset + FgbContGridXSize == FgbContGridYOffset) ? 1 : 0);
    private const int AssertFgbContGridY = 1 / ((FgbContGridYOffset + FgbContGridYSize == FgbContGridWOffset) ? 1 : 0);
    private const int AssertFgbContGridW = 1 / ((FgbContGridWOffset + FgbContGridWSize == FgbContGridHOffset) ? 1 : 0);
    private const int AssertFgbContGridH = 1 / ((FgbContGridHOffset + FgbContGridHSize == FgbContFillAmountOffset) ? 1 : 0);
    private const int AssertFgbContFillAmount = 1 / ((FgbContFillAmountOffset + FgbContFillAmountSize == FgbContReservedOffset) ? 1 : 0);
    private const int AssertFgbContReserved = 1 / ((FgbContReservedOffset + FgbContReservedSize == FgbContSize) ? 1 : 0);
    private const int AssertFgbLocalLocalId = 1 / ((FgbLocalLocalIdOffset + FgbLocalLocalIdSize == FgbLocalFlagsOffset) ? 1 : 0);
    private const int AssertFgbLocalFlags = 1 / ((FgbLocalFlagsOffset + FgbLocalFlagsSize == FgbLocalEditorIdStrOffset) ? 1 : 0);
    private const int AssertFgbLocalEditorIdStr = 1 / ((FgbLocalEditorIdStrOffset + FgbLocalEditorIdStrSize == FgbLocalNameStrOffset) ? 1 : 0);
    private const int AssertFgbLocalNameStr = 1 / ((FgbLocalNameStrOffset + FgbLocalNameStrSize == FgbLocalEditorIdHashOffset) ? 1 : 0);
    private const int AssertFgbLocalEditorIdHash = 1 / ((FgbLocalEditorIdHashOffset + FgbLocalEditorIdHashSize == FgbLocalSize) ? 1 : 0);
    private const int AssertFgbLeafLocalId = 1 / ((FgbLeafLocalIdOffset + FgbLeafLocalIdSize == FgbLeafTexSlotOffset) ? 1 : 0);
    private const int AssertFgbLeafTexSlot = 1 / ((FgbLeafTexSlotOffset + FgbLeafTexSlotSize == FgbLeafQuadStartOffset) ? 1 : 0);
    private const int AssertFgbLeafQuadStart = 1 / ((FgbLeafQuadStartOffset + FgbLeafQuadStartSize == FgbLeafQuadCountOffset) ? 1 : 0);
    private const int AssertFgbLeafQuadCount = 1 / ((FgbLeafQuadCountOffset + FgbLeafQuadCountSize == FgbLeafQuadSlackOffset) ? 1 : 0);
    private const int AssertFgbLeafQuadSlack = 1 / ((FgbLeafQuadSlackOffset + FgbLeafQuadSlackSize == FgbLeafSegmentOffset) ? 1 : 0);
    private const int AssertFgbLeafSegment = 1 / ((FgbLeafSegmentOffset + FgbLeafSegmentSize == FgbLeafRunOffset) ? 1 : 0);
    private const int AssertFgbLeafRun = 1 / ((FgbLeafRunOffset + FgbLeafRunSize == FgbLeafClipEntryOffset) ? 1 : 0);
    private const int AssertFgbLeafClipEntry = 1 / ((FgbLeafClipEntryOffset + FgbLeafClipEntrySize == FgbLeafSlotOffset) ? 1 : 0);
    private const int AssertFgbLeafSlot = 1 / ((FgbLeafSlotOffset + FgbLeafSlotSize == FgbLeafContentRefOffset) ? 1 : 0);
    private const int AssertFgbLeafContentRef = 1 / ((FgbLeafContentRefOffset + FgbLeafContentRefSize == FgbLeafEmitFlagsOffset) ? 1 : 0);
    private const int AssertFgbLeafEmitFlags = 1 / ((FgbLeafEmitFlagsOffset + FgbLeafEmitFlagsSize == FgbLeafSize) ? 1 : 0);
    private const int AssertFgbSegTex0 = 1 / ((FgbSegTex0Offset + FgbSegTex0Size == FgbSegTex1Offset) ? 1 : 0);
    private const int AssertFgbSegTex1 = 1 / ((FgbSegTex1Offset + FgbSegTex1Size == FgbSegTex2Offset) ? 1 : 0);
    private const int AssertFgbSegTex2 = 1 / ((FgbSegTex2Offset + FgbSegTex2Size == FgbSegTex3Offset) ? 1 : 0);
    private const int AssertFgbSegTex3 = 1 / ((FgbSegTex3Offset + FgbSegTex3Size == FgbSegTexCountOffset) ? 1 : 0);
    private const int AssertFgbSegTexCount = 1 / ((FgbSegTexCountOffset + FgbSegTexCountSize == FgbSegBlendOffset) ? 1 : 0);
    private const int AssertFgbSegBlend = 1 / ((FgbSegBlendOffset + FgbSegBlendSize == FgbSegReservedOffset) ? 1 : 0);
    private const int AssertFgbSegReserved = 1 / ((FgbSegReservedOffset + FgbSegReservedSize == FgbSegQuadStartOffset) ? 1 : 0);
    private const int AssertFgbSegQuadStart = 1 / ((FgbSegQuadStartOffset + FgbSegQuadStartSize == FgbSegQuadCountOffset) ? 1 : 0);
    private const int AssertFgbSegQuadCount = 1 / ((FgbSegQuadCountOffset + FgbSegQuadCountSize == FgbSegRunOffset) ? 1 : 0);
    private const int AssertFgbSegRun = 1 / ((FgbSegRunOffset + FgbSegRunSize == FgbSegSize) ? 1 : 0);
    private const int AssertFgbTexRefPkgId = 1 / ((FgbTexRefPkgIdOffset + FgbTexRefPkgIdSize == FgbTexRefItemStrOffset) ? 1 : 0);
    private const int AssertFgbTexRefItemStr = 1 / ((FgbTexRefItemStrOffset + FgbTexRefItemStrSize == FgbTexRefKindOffset) ? 1 : 0);
    private const int AssertFgbTexRefKind = 1 / ((FgbTexRefKindOffset + FgbTexRefKindSize == FgbTexRefTexIdOffset) ? 1 : 0);
    private const int AssertFgbTexRefTexId = 1 / ((FgbTexRefTexIdOffset + FgbTexRefTexIdSize == FgbTexRefSize) ? 1 : 0);
    private const int AssertFgbStrtHeaderCount = 1 / ((FgbStrtHeaderCountOffset + FgbStrtHeaderCountSize == FgbStrtHeaderPoolBytesOffset) ? 1 : 0);
    private const int AssertFgbStrtHeaderPoolBytes = 1 / ((FgbStrtHeaderPoolBytesOffset + FgbStrtHeaderPoolBytesSize == FgbStrtHeaderReservedOffset) ? 1 : 0);
    private const int AssertFgbStrtHeaderReserved = 1 / ((FgbStrtHeaderReservedOffset + FgbStrtHeaderReservedSize == FgbStrtHeaderSize) ? 1 : 0);
    private const int AssertFgbStrtEntryOffset = 1 / ((FgbStrtEntryOffsetOffset + FgbStrtEntryOffsetSize == FgbStrtEntryLengthOffset) ? 1 : 0);
    private const int AssertFgbStrtEntryLength = 1 / ((FgbStrtEntryLengthOffset + FgbStrtEntryLengthSize == FgbStrtEntrySize) ? 1 : 0);
    private const int AssertFgbCnstHeaderOpCount = 1 / ((FgbCnstHeaderOpCountOffset + FgbCnstHeaderOpCountSize == FgbCnstHeaderFanCountOffset) ? 1 : 0);
    private const int AssertFgbCnstHeaderFanCount = 1 / ((FgbCnstHeaderFanCountOffset + FgbCnstHeaderFanCountSize == FgbCnstHeaderIndexCountOffset) ? 1 : 0);
    private const int AssertFgbCnstHeaderIndexCount = 1 / ((FgbCnstHeaderIndexCountOffset + FgbCnstHeaderIndexCountSize == FgbCnstHeaderMaskCountOffset) ? 1 : 0);
    private const int AssertFgbCnstHeaderMaskCount = 1 / ((FgbCnstHeaderMaskCountOffset + FgbCnstHeaderMaskCountSize == FgbCnstHeaderSize) ? 1 : 0);

    /// <summary>
    /// 定义点交叉校验：本文件常量 vs <see cref="Abi"/> 数据表。null = 一致；
    /// 非 null = 首条不符的说明。表长变化亦在此暴露（生成物按当时表长展开）。
    /// </summary>
    public static string? Verify()
    {
        if (Abi.Scalars.Length != 20) return "Abi.Scalars 表长与生成物不符";
        if (Abi.Scalars[0].Value != FgbMagic) return "标量 FgbMagic 与生成物不符";
        if (Abi.Scalars[1].Value != FgbFormatVersion) return "标量 FgbFormatVersion 与生成物不符";
        if (Abi.Scalars[2].Value != FgbSectionAlignment) return "标量 FgbSectionAlignment 与生成物不符";
        if (Abi.Scalars[3].Value != QuadInstanceSize) return "标量 QuadInstanceSize 与生成物不符";
        if (Abi.Scalars[4].Value != QuadInstanceAlignment) return "标量 QuadInstanceAlignment 与生成物不符";
        if (Abi.Scalars[5].Value != ClipEntrySize) return "标量 ClipEntrySize 与生成物不符";
        if (Abi.Scalars[6].Value != ClipEntryAlignment) return "标量 ClipEntryAlignment 与生成物不符";
        if (Abi.Scalars[7].Value != SegmentMaxTextures) return "标量 SegmentMaxTextures 与生成物不符";
        if (Abi.Scalars[8].Value != PaintOrderStride) return "标量 PaintOrderStride 与生成物不符";
        if (Abi.Scalars[9].Value != ShaderAbiVersion) return "标量 ShaderAbiVersion 与生成物不符";
        if (Abi.Scalars[10].Value != TransformSlotBudget) return "标量 TransformSlotBudget 与生成物不符";
        if (Abi.Scalars[11].Value != ClipEntryBudget) return "标量 ClipEntryBudget 与生成物不符";
        if (Abi.Scalars[12].Value != GpuFenceDepth) return "标量 GpuFenceDepth 与生成物不符";
        if (Abi.Scalars[13].Value != MaxObservableProps) return "标量 MaxObservableProps 与生成物不符";
        if (Abi.Scalars[14].Value != CommandWaveLimit) return "标量 CommandWaveLimit 与生成物不符";
        if (Abi.Scalars[15].Value != LayoutMicroDrainLimit) return "标量 LayoutMicroDrainLimit 与生成物不符";
        if (Abi.Scalars[16].Value != FgbHeaderSize) return "标量 FgbHeaderSize 与生成物不符";
        if (Abi.Scalars[17].Value != FgbSectionDirEntrySize) return "标量 FgbSectionDirEntrySize 与生成物不符";
        if (Abi.Scalars[18].Value != NodeBytesPerNode) return "标量 NodeBytesPerNode 与生成物不符";
        if (Abi.Scalars[19].Value != FgbInstanceHeaderBytes) return "标量 FgbInstanceHeaderBytes 与生成物不符";
        if (Abi.QuadInstanceFields.Length != 8) return "Abi.QuadInstanceFields 表长与生成物不符";
        if (Abi.QuadInstanceFields[0].Offset != QuadRectOffset || Abi.QuadInstanceFields[0].Size != QuadRectSize) return "QuadRect 偏移/大小与生成物不符";
        if (Abi.QuadInstanceFields[1].Offset != QuadUvAOffset || Abi.QuadInstanceFields[1].Size != QuadUvASize) return "QuadUvA 偏移/大小与生成物不符";
        if (Abi.QuadInstanceFields[2].Offset != QuadUvBOffset || Abi.QuadInstanceFields[2].Size != QuadUvBSize) return "QuadUvB 偏移/大小与生成物不符";
        if (Abi.QuadInstanceFields[3].Offset != QuadColorOffset || Abi.QuadInstanceFields[3].Size != QuadColorSize) return "QuadColor 偏移/大小与生成物不符";
        if (Abi.QuadInstanceFields[4].Offset != QuadRouteOffset || Abi.QuadInstanceFields[4].Size != QuadRouteSize) return "QuadRoute 偏移/大小与生成物不符";
        if (Abi.QuadInstanceFields[5].Offset != QuadFlagsOffset || Abi.QuadInstanceFields[5].Size != QuadFlagsSize) return "QuadFlags 偏移/大小与生成物不符";
        if (Abi.QuadInstanceFields[6].Offset != QuadAuxOffset || Abi.QuadInstanceFields[6].Size != QuadAuxSize) return "QuadAux 偏移/大小与生成物不符";
        if (Abi.QuadInstanceFields[7].Offset != QuadExtraOffset || Abi.QuadInstanceFields[7].Size != QuadExtraSize) return "QuadExtra 偏移/大小与生成物不符";
        if (Abi.ClipEntryFields.Length != 5) return "Abi.ClipEntryFields 表长与生成物不符";
        if (Abi.ClipEntryFields[0].Offset != ClipRectOffset || Abi.ClipEntryFields[0].Size != ClipRectSize) return "ClipRect 偏移/大小与生成物不符";
        if (Abi.ClipEntryFields[1].Offset != ClipSoftOffset || Abi.ClipEntryFields[1].Size != ClipSoftSize) return "ClipSoft 偏移/大小与生成物不符";
        if (Abi.ClipEntryFields[2].Offset != ClipRadiiOffset || Abi.ClipEntryFields[2].Size != ClipRadiiSize) return "ClipRadii 偏移/大小与生成物不符";
        if (Abi.ClipEntryFields[3].Offset != ClipSlotOffset || Abi.ClipEntryFields[3].Size != ClipSlotSize) return "ClipSlot 偏移/大小与生成物不符";
        if (Abi.ClipEntryFields[4].Offset != ClipPadOffset || Abi.ClipEntryFields[4].Size != ClipPadSize) return "ClipPad 偏移/大小与生成物不符";
        if (Abi.RouteBits.Length != 4) return "Abi.RouteBits 表长与生成物不符";
        if (Abi.RouteBits[0].Shift != RouteSlotShift || Abi.RouteBits[0].Width != RouteSlotBits) return "RouteSlot 位域与生成物不符";
        if (Abi.RouteBits[1].Shift != RouteClipIndexShift || Abi.RouteBits[1].Width != RouteClipIndexBits) return "RouteClipIndex 位域与生成物不符";
        if (Abi.RouteBits[2].Shift != RouteTexSlotShift || Abi.RouteBits[2].Width != RouteTexSlotBits) return "RouteTexSlot 位域与生成物不符";
        if (Abi.RouteBits[3].Shift != RouteReservedShift || Abi.RouteBits[3].Width != RouteReservedBits) return "RouteReserved 位域与生成物不符";
        if (Abi.QuadFlagBits.Length != 9) return "Abi.QuadFlagBits 表长与生成物不符";
        if (Abi.QuadFlagBits[0].Shift != FlagsFontAlphaShift || Abi.QuadFlagBits[0].Width != FlagsFontAlphaBits) return "FlagsFontAlpha 位域与生成物不符";
        if (Abi.QuadFlagBits[1].Shift != FlagsSdfShift || Abi.QuadFlagBits[1].Width != FlagsSdfBits) return "FlagsSdf 位域与生成物不符";
        if (Abi.QuadFlagBits[2].Shift != FlagsCurveGlyphShift || Abi.QuadFlagBits[2].Width != FlagsCurveGlyphBits) return "FlagsCurveGlyph 位域与生成物不符";
        if (Abi.QuadFlagBits[3].Shift != FlagsGrayedShift || Abi.QuadFlagBits[3].Width != FlagsGrayedBits) return "FlagsGrayed 位域与生成物不符";
        if (Abi.QuadFlagBits[4].Shift != FlagsRadialFillShift || Abi.QuadFlagBits[4].Width != FlagsRadialFillBits) return "FlagsRadialFill 位域与生成物不符";
        if (Abi.QuadFlagBits[5].Shift != FlagsReservedLowShift || Abi.QuadFlagBits[5].Width != FlagsReservedLowBits) return "FlagsReservedLow 位域与生成物不符";
        if (Abi.QuadFlagBits[6].Shift != FlagsBorderWShift || Abi.QuadFlagBits[6].Width != FlagsBorderWBits) return "FlagsBorderW 位域与生成物不符";
        if (Abi.QuadFlagBits[7].Shift != FlagsTexSlotSpareShift || Abi.QuadFlagBits[7].Width != FlagsTexSlotSpareBits) return "FlagsTexSlotSpare 位域与生成物不符";
        if (Abi.QuadFlagBits[8].Shift != FlagsReservedHighShift || Abi.QuadFlagBits[8].Width != FlagsReservedHighBits) return "FlagsReservedHigh 位域与生成物不符";
        if (Abi.RadialFillAuxBits.Length != 5) return "Abi.RadialFillAuxBits 表长与生成物不符";
        if (Abi.RadialFillAuxBits[0].Shift != RadialFillMethodShift || Abi.RadialFillAuxBits[0].Width != RadialFillMethodBits) return "RadialFillMethod 位域与生成物不符";
        if (Abi.RadialFillAuxBits[1].Shift != RadialFillOriginShift || Abi.RadialFillAuxBits[1].Width != RadialFillOriginBits) return "RadialFillOrigin 位域与生成物不符";
        if (Abi.RadialFillAuxBits[2].Shift != RadialFillClockwiseShift || Abi.RadialFillAuxBits[2].Width != RadialFillClockwiseBits) return "RadialFillClockwise 位域与生成物不符";
        if (Abi.RadialFillAuxBits[3].Shift != RadialFillReservedShift || Abi.RadialFillAuxBits[3].Width != RadialFillReservedBits) return "RadialFillReserved 位域与生成物不符";
        if (Abi.RadialFillAuxBits[4].Shift != RadialFillAmountShift || Abi.RadialFillAuxBits[4].Width != RadialFillAmountBits) return "RadialFillAmount 位域与生成物不符";
        if (Abi.PropGroups.Length != 4) return "Abi.PropGroups 表长与生成物不符";
        if (Abi.PropGroups[0].First != PropGroupLayoutFirst || Abi.PropGroups[0].Last != PropGroupLayoutLast) return "分组 Layout 区间与生成物不符";
        if (Abi.PropGroups[1].First != PropGroupVisualFirst || Abi.PropGroups[1].Last != PropGroupVisualLast) return "分组 Visual 区间与生成物不符";
        if (Abi.PropGroups[2].First != PropGroupTextFirst || Abi.PropGroups[2].Last != PropGroupTextLast) return "分组 Text 区间与生成物不符";
        if (Abi.PropGroups[3].First != PropGroupTransformFirst || Abi.PropGroups[3].Last != PropGroupTransformLast) return "分组 Transform 区间与生成物不符";
        if (Abi.PropIds.Length != 16) return "Abi.PropIds 表长与生成物不符";
        if (Abi.PropIds[0].Id != PropIdWidth) return "PropId Width 与生成物不符";
        if (Abi.PropIds[1].Id != PropIdHeight) return "PropId Height 与生成物不符";
        if (Abi.PropIds[2].Id != PropIdAlpha) return "PropId Alpha 与生成物不符";
        if (Abi.PropIds[3].Id != PropIdVisible) return "PropId Visible 与生成物不符";
        if (Abi.PropIds[4].Id != PropIdGrayed) return "PropId Grayed 与生成物不符";
        if (Abi.PropIds[5].Id != PropIdColor) return "PropId Color 与生成物不符";
        if (Abi.PropIds[6].Id != PropIdTouchable) return "PropId Touchable 与生成物不符";
        if (Abi.PropIds[7].Id != PropIdTextId) return "PropId TextId 与生成物不符";
        if (Abi.PropIds[8].Id != PropIdFontSize) return "PropId FontSize 与生成物不符";
        if (Abi.PropIds[9].Id != PropIdX) return "PropId X 与生成物不符";
        if (Abi.PropIds[10].Id != PropIdY) return "PropId Y 与生成物不符";
        if (Abi.PropIds[11].Id != PropIdScaleX) return "PropId ScaleX 与生成物不符";
        if (Abi.PropIds[12].Id != PropIdScaleY) return "PropId ScaleY 与生成物不符";
        if (Abi.PropIds[13].Id != PropIdRotation) return "PropId Rotation 与生成物不符";
        if (Abi.PropIds[14].Id != PropIdSkew) return "PropId Skew 与生成物不符";
        if (Abi.PropIds[15].Id != PropIdPixelSnap) return "PropId PixelSnap 与生成物不符";
        if (Abi.FgbHeaderFields.Length != 11) return "Abi.FgbHeaderFields 表长与生成物不符";
        if (Abi.FgbHeaderFields[0].Offset != FgbHeaderMagicOffset || Abi.FgbHeaderFields[0].Size != FgbHeaderMagicSize) return "FgbHeaderMagic 偏移/大小与生成物不符";
        if (Abi.FgbHeaderFields[1].Offset != FgbHeaderFormatVersionOffset || Abi.FgbHeaderFields[1].Size != FgbHeaderFormatVersionSize) return "FgbHeaderFormatVersion 偏移/大小与生成物不符";
        if (Abi.FgbHeaderFields[2].Offset != FgbHeaderFlagsOffset || Abi.FgbHeaderFields[2].Size != FgbHeaderFlagsSize) return "FgbHeaderFlags 偏移/大小与生成物不符";
        if (Abi.FgbHeaderFields[3].Offset != FgbHeaderReserved0Offset || Abi.FgbHeaderFields[3].Size != FgbHeaderReserved0Size) return "FgbHeaderReserved0 偏移/大小与生成物不符";
        if (Abi.FgbHeaderFields[4].Offset != FgbHeaderSelfHashOffset || Abi.FgbHeaderFields[4].Size != FgbHeaderSelfHashSize) return "FgbHeaderSelfHash 偏移/大小与生成物不符";
        if (Abi.FgbHeaderFields[5].Offset != FgbHeaderSourceHashOffset || Abi.FgbHeaderFields[5].Size != FgbHeaderSourceHashSize) return "FgbHeaderSourceHash 偏移/大小与生成物不符";
        if (Abi.FgbHeaderFields[6].Offset != FgbHeaderCombinedRefHashOffset || Abi.FgbHeaderFields[6].Size != FgbHeaderCombinedRefHashSize) return "FgbHeaderCombinedRefHash 偏移/大小与生成物不符";
        if (Abi.FgbHeaderFields[7].Offset != FgbHeaderScaleLevelOffset || Abi.FgbHeaderFields[7].Size != FgbHeaderScaleLevelSize) return "FgbHeaderScaleLevel 偏移/大小与生成物不符";
        if (Abi.FgbHeaderFields[8].Offset != FgbHeaderBranchIdOffset || Abi.FgbHeaderFields[8].Size != FgbHeaderBranchIdSize) return "FgbHeaderBranchId 偏移/大小与生成物不符";
        if (Abi.FgbHeaderFields[9].Offset != FgbHeaderSectionCountOffset || Abi.FgbHeaderFields[9].Size != FgbHeaderSectionCountSize) return "FgbHeaderSectionCount 偏移/大小与生成物不符";
        if (Abi.FgbHeaderFields[10].Offset != FgbHeaderReserved1Offset || Abi.FgbHeaderFields[10].Size != FgbHeaderReserved1Size) return "FgbHeaderReserved1 偏移/大小与生成物不符";
        if (Abi.FgbSectionDirFields.Length != 4) return "Abi.FgbSectionDirFields 表长与生成物不符";
        if (Abi.FgbSectionDirFields[0].Offset != FgbDirFourccOffset || Abi.FgbSectionDirFields[0].Size != FgbDirFourccSize) return "FgbDirFourcc 偏移/大小与生成物不符";
        if (Abi.FgbSectionDirFields[1].Offset != FgbDirReservedOffset || Abi.FgbSectionDirFields[1].Size != FgbDirReservedSize) return "FgbDirReserved 偏移/大小与生成物不符";
        if (Abi.FgbSectionDirFields[2].Offset != FgbDirOffsetOffset || Abi.FgbSectionDirFields[2].Size != FgbDirOffsetSize) return "FgbDirOffset 偏移/大小与生成物不符";
        if (Abi.FgbSectionDirFields[3].Offset != FgbDirLengthOffset || Abi.FgbSectionDirFields[3].Size != FgbDirLengthSize) return "FgbDirLength 偏移/大小与生成物不符";
        if (Abi.FgbFlagBits.Length != 3) return "Abi.FgbFlagBits 表长与生成物不符";
        if (Abi.FgbFlagBits[0].Shift != FgbFlagLittleEndianShift || Abi.FgbFlagBits[0].Width != FgbFlagLittleEndianBits) return "FgbFlagLittleEndian 位域与生成物不符";
        if (Abi.FgbFlagBits[1].Shift != FgbFlagCompressedShift || Abi.FgbFlagBits[1].Width != FgbFlagCompressedBits) return "FgbFlagCompressed 位域与生成物不符";
        if (Abi.FgbFlagBits[2].Shift != FgbFlagReservedShift || Abi.FgbFlagBits[2].Width != FgbFlagReservedBits) return "FgbFlagReserved 位域与生成物不符";
        if (Abi.FgbSectionIds.Length != 20) return "Abi.FgbSectionIds 表长与生成物不符";
        if (Abi.FgbSectionIds[0].Value != FgbSectionStrt) return "fourcc Strt 与生成物不符";
        if (Abi.FgbSectionIds[1].Value != FgbSectionLang) return "fourcc Lang 与生成物不符";
        if (Abi.FgbSectionIds[2].Value != FgbSectionComp) return "fourcc Comp 与生成物不符";
        if (Abi.FgbSectionIds[3].Value != FgbSectionNode) return "fourcc Node 与生成物不符";
        if (Abi.FgbSectionIds[4].Value != FgbSectionPlan) return "fourcc Plan 与生成物不符";
        if (Abi.FgbSectionIds[5].Value != FgbSectionQuad) return "fourcc Quad 与生成物不符";
        if (Abi.FgbSectionIds[6].Value != FgbSectionSegs) return "fourcc Segs 与生成物不符";
        if (Abi.FgbSectionIds[7].Value != FgbSectionLeaf) return "fourcc Leaf 与生成物不符";
        if (Abi.FgbSectionIds[8].Value != FgbSectionClip) return "fourcc Clip 与生成物不符";
        if (Abi.FgbSectionIds[9].Value != FgbSectionPtch) return "fourcc Ptch 与生成物不符";
        if (Abi.FgbSectionIds[10].Value != FgbSectionCnst) return "fourcc Cnst 与生成物不符";
        if (Abi.FgbSectionIds[11].Value != FgbSectionBind) return "fourcc Bind 与生成物不符";
        if (Abi.FgbSectionIds[12].Value != FgbSectionAnim) return "fourcc Anim 与生成物不符";
        if (Abi.FgbSectionIds[13].Value != FgbSectionSprt) return "fourcc Sprt 与生成物不符";
        if (Abi.FgbSectionIds[14].Value != FgbSectionTref) return "fourcc Tref 与生成物不符";
        if (Abi.FgbSectionIds[15].Value != FgbSectionDeps) return "fourcc Deps 与生成物不符";
        if (Abi.FgbSectionIds[16].Value != FgbSectionHitt) return "fourcc Hitt 与生成物不符";
        if (Abi.FgbSectionIds[17].Value != FgbSectionBrch) return "fourcc Brch 与生成物不符";
        if (Abi.FgbSectionIds[18].Value != FgbSectionCont) return "fourcc Cont 与生成物不符";
        if (Abi.FgbSectionIds[19].Value != FgbSectionLocl) return "fourcc Locl 与生成物不符";
        if (Abi.NodeColumns.Length != NodeColumnCount) return "Abi.NodeColumns 表长与生成物不符";
        if (Abi.NodeColumns[0].ElementSize != NodeColParentSize || Abi.NodeColumns[0].Rebase != NodeColParentRebase) return "NODE 列 Parent 与生成物不符";
        if (Abi.NodeColumns[1].ElementSize != NodeColFirstChildSize || Abi.NodeColumns[1].Rebase != NodeColFirstChildRebase) return "NODE 列 FirstChild 与生成物不符";
        if (Abi.NodeColumns[2].ElementSize != NodeColNextSibSize || Abi.NodeColumns[2].Rebase != NodeColNextSibRebase) return "NODE 列 NextSib 与生成物不符";
        if (Abi.NodeColumns[3].ElementSize != NodeColPrevSibSize || Abi.NodeColumns[3].Rebase != NodeColPrevSibRebase) return "NODE 列 PrevSib 与生成物不符";
        if (Abi.NodeColumns[4].ElementSize != NodeColOwnerInstSize || Abi.NodeColumns[4].Rebase != NodeColOwnerInstRebase) return "NODE 列 OwnerInst 与生成物不符";
        if (Abi.NodeColumns[5].ElementSize != NodeColLocalIdSize || Abi.NodeColumns[5].Rebase != NodeColLocalIdRebase) return "NODE 列 LocalId 与生成物不符";
        if (Abi.NodeColumns[6].ElementSize != NodeColTypeIdSize || Abi.NodeColumns[6].Rebase != NodeColTypeIdRebase) return "NODE 列 TypeId 与生成物不符";
        if (Abi.NodeColumns[7].ElementSize != NodeColPosXSize || Abi.NodeColumns[7].Rebase != NodeColPosXRebase) return "NODE 列 PosX 与生成物不符";
        if (Abi.NodeColumns[8].ElementSize != NodeColPosYSize || Abi.NodeColumns[8].Rebase != NodeColPosYRebase) return "NODE 列 PosY 与生成物不符";
        if (Abi.NodeColumns[9].ElementSize != NodeColWidthSize || Abi.NodeColumns[9].Rebase != NodeColWidthRebase) return "NODE 列 Width 与生成物不符";
        if (Abi.NodeColumns[10].ElementSize != NodeColHeightSize || Abi.NodeColumns[10].Rebase != NodeColHeightRebase) return "NODE 列 Height 与生成物不符";
        if (Abi.NodeColumns[11].ElementSize != NodeColScaleXSize || Abi.NodeColumns[11].Rebase != NodeColScaleXRebase) return "NODE 列 ScaleX 与生成物不符";
        if (Abi.NodeColumns[12].ElementSize != NodeColScaleYSize || Abi.NodeColumns[12].Rebase != NodeColScaleYRebase) return "NODE 列 ScaleY 与生成物不符";
        if (Abi.NodeColumns[13].ElementSize != NodeColRotationSize || Abi.NodeColumns[13].Rebase != NodeColRotationRebase) return "NODE 列 Rotation 与生成物不符";
        if (Abi.NodeColumns[14].ElementSize != NodeColSkewSize || Abi.NodeColumns[14].Rebase != NodeColSkewRebase) return "NODE 列 Skew 与生成物不符";
        if (Abi.NodeColumns[15].ElementSize != NodeColPivotXSize || Abi.NodeColumns[15].Rebase != NodeColPivotXRebase) return "NODE 列 PivotX 与生成物不符";
        if (Abi.NodeColumns[16].ElementSize != NodeColPivotYSize || Abi.NodeColumns[16].Rebase != NodeColPivotYRebase) return "NODE 列 PivotY 与生成物不符";
        if (Abi.NodeColumns[17].ElementSize != NodeColLocalVisualSize || Abi.NodeColumns[17].Rebase != NodeColLocalVisualRebase) return "NODE 列 LocalVisual 与生成物不符";
        if (Abi.NodeColumns[18].ElementSize != NodeColContentRefSize || Abi.NodeColumns[18].Rebase != NodeColContentRefRebase) return "NODE 列 ContentRef 与生成物不符";
        if (Abi.NodeColumns[19].ElementSize != NodeColStateRefSize || Abi.NodeColumns[19].Rebase != NodeColStateRefRebase) return "NODE 列 StateRef 与生成物不符";
        if (Abi.NodeColumns[20].ElementSize != NodeColResolvedRefSize || Abi.NodeColumns[20].Rebase != NodeColResolvedRefRebase) return "NODE 列 ResolvedRef 与生成物不符";
        if (Abi.FgbRecords.Length != 9) return "Abi.FgbRecords 表长与生成物不符";
        if (Abi.FgbRecords[0].Size != FgbCompSize) return "记录 Comp 定长与生成物不符";
        if (Abi.FgbRecords[0].Fields.Length != 25) return "Abi.FgbRecords[0].Fields 表长与生成物不符";
        if (Abi.FgbRecords[0].Fields[0].Offset != FgbCompNameStrOffset || Abi.FgbRecords[0].Fields[0].Size != FgbCompNameStrSize) return "FgbCompNameStr 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[1].Offset != FgbCompNameHashOffset || Abi.FgbRecords[0].Fields[1].Size != FgbCompNameHashSize) return "FgbCompNameHash 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[2].Offset != FgbCompNodeStartOffset || Abi.FgbRecords[0].Fields[2].Size != FgbCompNodeStartSize) return "FgbCompNodeStart 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[3].Offset != FgbCompNodeCountOffset || Abi.FgbRecords[0].Fields[3].Size != FgbCompNodeCountSize) return "FgbCompNodeCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[4].Offset != FgbCompQuadStartOffset || Abi.FgbRecords[0].Fields[4].Size != FgbCompQuadStartSize) return "FgbCompQuadStart 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[5].Offset != FgbCompQuadCountOffset || Abi.FgbRecords[0].Fields[5].Size != FgbCompQuadCountSize) return "FgbCompQuadCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[6].Offset != FgbCompSegStartOffset || Abi.FgbRecords[0].Fields[6].Size != FgbCompSegStartSize) return "FgbCompSegStart 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[7].Offset != FgbCompSegCountOffset || Abi.FgbRecords[0].Fields[7].Size != FgbCompSegCountSize) return "FgbCompSegCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[8].Offset != FgbCompLeafStartOffset || Abi.FgbRecords[0].Fields[8].Size != FgbCompLeafStartSize) return "FgbCompLeafStart 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[9].Offset != FgbCompLeafCountOffset || Abi.FgbRecords[0].Fields[9].Size != FgbCompLeafCountSize) return "FgbCompLeafCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[10].Offset != FgbCompClipStartOffset || Abi.FgbRecords[0].Fields[10].Size != FgbCompClipStartSize) return "FgbCompClipStart 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[11].Offset != FgbCompClipCountOffset || Abi.FgbRecords[0].Fields[11].Size != FgbCompClipCountSize) return "FgbCompClipCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[12].Offset != FgbCompCnstOpStartOffset || Abi.FgbRecords[0].Fields[12].Size != FgbCompCnstOpStartSize) return "FgbCompCnstOpStart 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[13].Offset != FgbCompCnstOpCountOffset || Abi.FgbRecords[0].Fields[13].Size != FgbCompCnstOpCountSize) return "FgbCompCnstOpCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[14].Offset != FgbCompCnstFanStartOffset || Abi.FgbRecords[0].Fields[14].Size != FgbCompCnstFanStartSize) return "FgbCompCnstFanStart 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[15].Offset != FgbCompCnstIdxStartOffset || Abi.FgbRecords[0].Fields[15].Size != FgbCompCnstIdxStartSize) return "FgbCompCnstIdxStart 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[16].Offset != FgbCompCnstIdxCountOffset || Abi.FgbRecords[0].Fields[16].Size != FgbCompCnstIdxCountSize) return "FgbCompCnstIdxCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[17].Offset != FgbCompLocalStartOffset || Abi.FgbRecords[0].Fields[17].Size != FgbCompLocalStartSize) return "FgbCompLocalStart 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[18].Offset != FgbCompLocalCountOffset || Abi.FgbRecords[0].Fields[18].Size != FgbCompLocalCountSize) return "FgbCompLocalCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[19].Offset != FgbCompInstanceBytesOffset || Abi.FgbRecords[0].Fields[19].Size != FgbCompInstanceBytesSize) return "FgbCompInstanceBytes 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[20].Offset != FgbCompSourceWidthOffset || Abi.FgbRecords[0].Fields[20].Size != FgbCompSourceWidthSize) return "FgbCompSourceWidth 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[21].Offset != FgbCompSourceHeightOffset || Abi.FgbRecords[0].Fields[21].Size != FgbCompSourceHeightSize) return "FgbCompSourceHeight 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[22].Offset != FgbCompCtrlCountOffset || Abi.FgbRecords[0].Fields[22].Size != FgbCompCtrlCountSize) return "FgbCompCtrlCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[23].Offset != FgbCompFlagsOffset || Abi.FgbRecords[0].Fields[23].Size != FgbCompFlagsSize) return "FgbCompFlags 偏移/大小与生成物不符";
        if (Abi.FgbRecords[0].Fields[24].Offset != FgbCompReservedOffset || Abi.FgbRecords[0].Fields[24].Size != FgbCompReservedSize) return "FgbCompReserved 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Size != FgbContSize) return "记录 Cont 定长与生成物不符";
        if (Abi.FgbRecords[1].Fields.Length != 22) return "Abi.FgbRecords[1].Fields 表长与生成物不符";
        if (Abi.FgbRecords[1].Fields[0].Offset != FgbContKindOffset || Abi.FgbRecords[1].Fields[0].Size != FgbContKindSize) return "FgbContKind 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[1].Offset != FgbContBlendOffset || Abi.FgbRecords[1].Fields[1].Size != FgbContBlendSize) return "FgbContBlend 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[2].Offset != FgbContFlagsOffset || Abi.FgbRecords[1].Fields[2].Size != FgbContFlagsSize) return "FgbContFlags 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[3].Offset != FgbContTexIdOffset || Abi.FgbRecords[1].Fields[3].Size != FgbContTexIdSize) return "FgbContTexId 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[4].Offset != FgbContBaseColorOffset || Abi.FgbRecords[1].Fields[4].Size != FgbContBaseColorSize) return "FgbContBaseColor 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[5].Offset != FgbContEmitFlagsOffset || Abi.FgbRecords[1].Fields[5].Size != FgbContEmitFlagsSize) return "FgbContEmitFlags 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[6].Offset != FgbContSlackHintOffset || Abi.FgbRecords[1].Fields[6].Size != FgbContSlackHintSize) return "FgbContSlackHint 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[7].Offset != FgbContTileGridIndiceOffset || Abi.FgbRecords[1].Fields[7].Size != FgbContTileGridIndiceSize) return "FgbContTileGridIndice 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[8].Offset != FgbContTextStrOffset || Abi.FgbRecords[1].Fields[8].Size != FgbContTextStrSize) return "FgbContTextStr 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[9].Offset != FgbContFillPackOffset || Abi.FgbRecords[1].Fields[9].Size != FgbContFillPackSize) return "FgbContFillPack 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[10].Offset != FgbContUvX0Offset || Abi.FgbRecords[1].Fields[10].Size != FgbContUvX0Size) return "FgbContUvX0 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[11].Offset != FgbContUvY0Offset || Abi.FgbRecords[1].Fields[11].Size != FgbContUvY0Size) return "FgbContUvY0 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[12].Offset != FgbContUvX1Offset || Abi.FgbRecords[1].Fields[12].Size != FgbContUvX1Size) return "FgbContUvX1 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[13].Offset != FgbContUvY1Offset || Abi.FgbRecords[1].Fields[13].Size != FgbContUvY1Size) return "FgbContUvY1 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[14].Offset != FgbContSourceWidthOffset || Abi.FgbRecords[1].Fields[14].Size != FgbContSourceWidthSize) return "FgbContSourceWidth 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[15].Offset != FgbContSourceHeightOffset || Abi.FgbRecords[1].Fields[15].Size != FgbContSourceHeightSize) return "FgbContSourceHeight 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[16].Offset != FgbContGridXOffset || Abi.FgbRecords[1].Fields[16].Size != FgbContGridXSize) return "FgbContGridX 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[17].Offset != FgbContGridYOffset || Abi.FgbRecords[1].Fields[17].Size != FgbContGridYSize) return "FgbContGridY 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[18].Offset != FgbContGridWOffset || Abi.FgbRecords[1].Fields[18].Size != FgbContGridWSize) return "FgbContGridW 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[19].Offset != FgbContGridHOffset || Abi.FgbRecords[1].Fields[19].Size != FgbContGridHSize) return "FgbContGridH 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[20].Offset != FgbContFillAmountOffset || Abi.FgbRecords[1].Fields[20].Size != FgbContFillAmountSize) return "FgbContFillAmount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[1].Fields[21].Offset != FgbContReservedOffset || Abi.FgbRecords[1].Fields[21].Size != FgbContReservedSize) return "FgbContReserved 偏移/大小与生成物不符";
        if (Abi.FgbRecords[2].Size != FgbLocalSize) return "记录 Local 定长与生成物不符";
        if (Abi.FgbRecords[2].Fields.Length != 5) return "Abi.FgbRecords[2].Fields 表长与生成物不符";
        if (Abi.FgbRecords[2].Fields[0].Offset != FgbLocalLocalIdOffset || Abi.FgbRecords[2].Fields[0].Size != FgbLocalLocalIdSize) return "FgbLocalLocalId 偏移/大小与生成物不符";
        if (Abi.FgbRecords[2].Fields[1].Offset != FgbLocalFlagsOffset || Abi.FgbRecords[2].Fields[1].Size != FgbLocalFlagsSize) return "FgbLocalFlags 偏移/大小与生成物不符";
        if (Abi.FgbRecords[2].Fields[2].Offset != FgbLocalEditorIdStrOffset || Abi.FgbRecords[2].Fields[2].Size != FgbLocalEditorIdStrSize) return "FgbLocalEditorIdStr 偏移/大小与生成物不符";
        if (Abi.FgbRecords[2].Fields[3].Offset != FgbLocalNameStrOffset || Abi.FgbRecords[2].Fields[3].Size != FgbLocalNameStrSize) return "FgbLocalNameStr 偏移/大小与生成物不符";
        if (Abi.FgbRecords[2].Fields[4].Offset != FgbLocalEditorIdHashOffset || Abi.FgbRecords[2].Fields[4].Size != FgbLocalEditorIdHashSize) return "FgbLocalEditorIdHash 偏移/大小与生成物不符";
        if (Abi.FgbRecords[3].Size != FgbLeafSize) return "记录 Leaf 定长与生成物不符";
        if (Abi.FgbRecords[3].Fields.Length != 11) return "Abi.FgbRecords[3].Fields 表长与生成物不符";
        if (Abi.FgbRecords[3].Fields[0].Offset != FgbLeafLocalIdOffset || Abi.FgbRecords[3].Fields[0].Size != FgbLeafLocalIdSize) return "FgbLeafLocalId 偏移/大小与生成物不符";
        if (Abi.FgbRecords[3].Fields[1].Offset != FgbLeafTexSlotOffset || Abi.FgbRecords[3].Fields[1].Size != FgbLeafTexSlotSize) return "FgbLeafTexSlot 偏移/大小与生成物不符";
        if (Abi.FgbRecords[3].Fields[2].Offset != FgbLeafQuadStartOffset || Abi.FgbRecords[3].Fields[2].Size != FgbLeafQuadStartSize) return "FgbLeafQuadStart 偏移/大小与生成物不符";
        if (Abi.FgbRecords[3].Fields[3].Offset != FgbLeafQuadCountOffset || Abi.FgbRecords[3].Fields[3].Size != FgbLeafQuadCountSize) return "FgbLeafQuadCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[3].Fields[4].Offset != FgbLeafQuadSlackOffset || Abi.FgbRecords[3].Fields[4].Size != FgbLeafQuadSlackSize) return "FgbLeafQuadSlack 偏移/大小与生成物不符";
        if (Abi.FgbRecords[3].Fields[5].Offset != FgbLeafSegmentOffset || Abi.FgbRecords[3].Fields[5].Size != FgbLeafSegmentSize) return "FgbLeafSegment 偏移/大小与生成物不符";
        if (Abi.FgbRecords[3].Fields[6].Offset != FgbLeafRunOffset || Abi.FgbRecords[3].Fields[6].Size != FgbLeafRunSize) return "FgbLeafRun 偏移/大小与生成物不符";
        if (Abi.FgbRecords[3].Fields[7].Offset != FgbLeafClipEntryOffset || Abi.FgbRecords[3].Fields[7].Size != FgbLeafClipEntrySize) return "FgbLeafClipEntry 偏移/大小与生成物不符";
        if (Abi.FgbRecords[3].Fields[8].Offset != FgbLeafSlotOffset || Abi.FgbRecords[3].Fields[8].Size != FgbLeafSlotSize) return "FgbLeafSlot 偏移/大小与生成物不符";
        if (Abi.FgbRecords[3].Fields[9].Offset != FgbLeafContentRefOffset || Abi.FgbRecords[3].Fields[9].Size != FgbLeafContentRefSize) return "FgbLeafContentRef 偏移/大小与生成物不符";
        if (Abi.FgbRecords[3].Fields[10].Offset != FgbLeafEmitFlagsOffset || Abi.FgbRecords[3].Fields[10].Size != FgbLeafEmitFlagsSize) return "FgbLeafEmitFlags 偏移/大小与生成物不符";
        if (Abi.FgbRecords[4].Size != FgbSegSize) return "记录 Seg 定长与生成物不符";
        if (Abi.FgbRecords[4].Fields.Length != 10) return "Abi.FgbRecords[4].Fields 表长与生成物不符";
        if (Abi.FgbRecords[4].Fields[0].Offset != FgbSegTex0Offset || Abi.FgbRecords[4].Fields[0].Size != FgbSegTex0Size) return "FgbSegTex0 偏移/大小与生成物不符";
        if (Abi.FgbRecords[4].Fields[1].Offset != FgbSegTex1Offset || Abi.FgbRecords[4].Fields[1].Size != FgbSegTex1Size) return "FgbSegTex1 偏移/大小与生成物不符";
        if (Abi.FgbRecords[4].Fields[2].Offset != FgbSegTex2Offset || Abi.FgbRecords[4].Fields[2].Size != FgbSegTex2Size) return "FgbSegTex2 偏移/大小与生成物不符";
        if (Abi.FgbRecords[4].Fields[3].Offset != FgbSegTex3Offset || Abi.FgbRecords[4].Fields[3].Size != FgbSegTex3Size) return "FgbSegTex3 偏移/大小与生成物不符";
        if (Abi.FgbRecords[4].Fields[4].Offset != FgbSegTexCountOffset || Abi.FgbRecords[4].Fields[4].Size != FgbSegTexCountSize) return "FgbSegTexCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[4].Fields[5].Offset != FgbSegBlendOffset || Abi.FgbRecords[4].Fields[5].Size != FgbSegBlendSize) return "FgbSegBlend 偏移/大小与生成物不符";
        if (Abi.FgbRecords[4].Fields[6].Offset != FgbSegReservedOffset || Abi.FgbRecords[4].Fields[6].Size != FgbSegReservedSize) return "FgbSegReserved 偏移/大小与生成物不符";
        if (Abi.FgbRecords[4].Fields[7].Offset != FgbSegQuadStartOffset || Abi.FgbRecords[4].Fields[7].Size != FgbSegQuadStartSize) return "FgbSegQuadStart 偏移/大小与生成物不符";
        if (Abi.FgbRecords[4].Fields[8].Offset != FgbSegQuadCountOffset || Abi.FgbRecords[4].Fields[8].Size != FgbSegQuadCountSize) return "FgbSegQuadCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[4].Fields[9].Offset != FgbSegRunOffset || Abi.FgbRecords[4].Fields[9].Size != FgbSegRunSize) return "FgbSegRun 偏移/大小与生成物不符";
        if (Abi.FgbRecords[5].Size != FgbTexRefSize) return "记录 TexRef 定长与生成物不符";
        if (Abi.FgbRecords[5].Fields.Length != 4) return "Abi.FgbRecords[5].Fields 表长与生成物不符";
        if (Abi.FgbRecords[5].Fields[0].Offset != FgbTexRefPkgIdOffset || Abi.FgbRecords[5].Fields[0].Size != FgbTexRefPkgIdSize) return "FgbTexRefPkgId 偏移/大小与生成物不符";
        if (Abi.FgbRecords[5].Fields[1].Offset != FgbTexRefItemStrOffset || Abi.FgbRecords[5].Fields[1].Size != FgbTexRefItemStrSize) return "FgbTexRefItemStr 偏移/大小与生成物不符";
        if (Abi.FgbRecords[5].Fields[2].Offset != FgbTexRefKindOffset || Abi.FgbRecords[5].Fields[2].Size != FgbTexRefKindSize) return "FgbTexRefKind 偏移/大小与生成物不符";
        if (Abi.FgbRecords[5].Fields[3].Offset != FgbTexRefTexIdOffset || Abi.FgbRecords[5].Fields[3].Size != FgbTexRefTexIdSize) return "FgbTexRefTexId 偏移/大小与生成物不符";
        if (Abi.FgbRecords[6].Size != FgbStrtHeaderSize) return "记录 StrtHeader 定长与生成物不符";
        if (Abi.FgbRecords[6].Fields.Length != 3) return "Abi.FgbRecords[6].Fields 表长与生成物不符";
        if (Abi.FgbRecords[6].Fields[0].Offset != FgbStrtHeaderCountOffset || Abi.FgbRecords[6].Fields[0].Size != FgbStrtHeaderCountSize) return "FgbStrtHeaderCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[6].Fields[1].Offset != FgbStrtHeaderPoolBytesOffset || Abi.FgbRecords[6].Fields[1].Size != FgbStrtHeaderPoolBytesSize) return "FgbStrtHeaderPoolBytes 偏移/大小与生成物不符";
        if (Abi.FgbRecords[6].Fields[2].Offset != FgbStrtHeaderReservedOffset || Abi.FgbRecords[6].Fields[2].Size != FgbStrtHeaderReservedSize) return "FgbStrtHeaderReserved 偏移/大小与生成物不符";
        if (Abi.FgbRecords[7].Size != FgbStrtEntrySize) return "记录 StrtEntry 定长与生成物不符";
        if (Abi.FgbRecords[7].Fields.Length != 2) return "Abi.FgbRecords[7].Fields 表长与生成物不符";
        if (Abi.FgbRecords[7].Fields[0].Offset != FgbStrtEntryOffsetOffset || Abi.FgbRecords[7].Fields[0].Size != FgbStrtEntryOffsetSize) return "FgbStrtEntryOffset 偏移/大小与生成物不符";
        if (Abi.FgbRecords[7].Fields[1].Offset != FgbStrtEntryLengthOffset || Abi.FgbRecords[7].Fields[1].Size != FgbStrtEntryLengthSize) return "FgbStrtEntryLength 偏移/大小与生成物不符";
        if (Abi.FgbRecords[8].Size != FgbCnstHeaderSize) return "记录 CnstHeader 定长与生成物不符";
        if (Abi.FgbRecords[8].Fields.Length != 4) return "Abi.FgbRecords[8].Fields 表长与生成物不符";
        if (Abi.FgbRecords[8].Fields[0].Offset != FgbCnstHeaderOpCountOffset || Abi.FgbRecords[8].Fields[0].Size != FgbCnstHeaderOpCountSize) return "FgbCnstHeaderOpCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[8].Fields[1].Offset != FgbCnstHeaderFanCountOffset || Abi.FgbRecords[8].Fields[1].Size != FgbCnstHeaderFanCountSize) return "FgbCnstHeaderFanCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[8].Fields[2].Offset != FgbCnstHeaderIndexCountOffset || Abi.FgbRecords[8].Fields[2].Size != FgbCnstHeaderIndexCountSize) return "FgbCnstHeaderIndexCount 偏移/大小与生成物不符";
        if (Abi.FgbRecords[8].Fields[3].Offset != FgbCnstHeaderMaskCountOffset || Abi.FgbRecords[8].Fields[3].Size != FgbCnstHeaderMaskCountSize) return "FgbCnstHeaderMaskCount 偏移/大小与生成物不符";
        return null;
    }
}
