using System.Collections.Generic;
using System.Globalization;
using System.Text;
using FairyNext.Contracts;

namespace FairyNext.AbiGen;

/// <summary>
/// ABI 三份生成物的纯函数产出（M1-01）。输入只有 <see cref="Abi"/> 的静态数据表，
/// 输出只有字符串——**没有时间、没有环境变量、没有绝对路径、没有并发**，
/// 同一份 Abi.cs 在任何机器上产出同一批字节（架构文档「编译平面」契约执法①）。
///
/// 输出顺序 = Abi.cs 表内声明序。重排表即重排生成物即比对门变红，这是有意的。
/// </summary>
public static class AbiGenerator
{
    public const string CsLayoutPath = "src/Contracts/Abi.Layout.g.cs";
    public const string MockPath = "src/Backend.Mock/AbiMock.g.cs";
    public const string HlslPath = "shaders/abi.g.hlsl";

    private const string QuadPrefix = "Quad";
    private const string ClipPrefix = "Clip";
    private const string RoutePrefix = "Route";
    private const string FlagsPrefix = "Flags";
    private const string RadialFillPrefix = "RadialFill";

    private static readonly UTF8Encoding Utf8NoBom = new UTF8Encoding(false);

    /// <summary>三份生成物，顺序固定（C# 布局 → mock 常量 → HLSL include）。</summary>
    public static GeneratedFile[] GenerateAll() => new[]
    {
        new GeneratedFile(CsLayoutPath, GenerateCsLayout()),
        new GeneratedFile(MockPath, GenerateMock()),
        new GeneratedFile(HlslPath, GenerateHlsl()),
    };

    /// <summary>文本 → 落盘字节：无 BOM UTF-8。字节比对门比的就是这一串。</summary>
    public static byte[] Encode(string text) => Utf8NoBom.GetBytes(text);

    // ========================================================================
    // 生成物 1：src/Contracts/Abi.Layout.g.cs
    // ========================================================================
    public static string GenerateCsLayout()
    {
        var o = new TextOut();
        EmitCsHeader(o, "偏移/大小/位域常量 + 定义点交叉校验。");
        o.Line("namespace FairyNext.Contracts;");
        o.Line();
        o.Line("/// <summary>");
        o.Line("/// QuadInstance / ClipEntry 的字节布局、route/flags 位域、PropId 与预算常量。");
        o.Line("/// 生成物；定义点是 <see cref=\"Abi\"/> 的静态数据表。");
        o.Line("/// </summary>");
        o.Line("public static class AbiLayout");
        o.Line("{");
        EmitCsBody(o, includeVerify: true);
        o.Line("}");
        return o.ToString();
    }

    // ========================================================================
    // 生成物 2：src/Backend.Mock/AbiMock.g.cs
    // ========================================================================
    public static string GenerateMock()
    {
        var o = new TextOut();
        EmitCsHeader(o, "mock 后端侧的同一组常量（独立副本）。",
            "// mock 后端不引用 FairyNext.Contracts：无 GPU 行为门的宿主必须能独立复述 ABI，\n"
            + "// 否则「两侧同意」退化为「同一个变量读了两次」。两份副本同源生成，漂移由字节比对门拦。");
        o.Line("namespace FairyNext.Backend.Mock;");
        o.Line();
        o.Line("/// <summary>");
        o.Line("/// mock 后端的 ABI 常量副本。定义点是 src/Contracts/Abi.cs 的静态数据表。");
        o.Line("/// </summary>");
        o.Line("public static class AbiMock");
        o.Line("{");
        EmitCsBody(o, includeVerify: false);
        o.Line("}");
        return o.ToString();
    }

    // ========================================================================
    // 生成物 3：shaders/abi.g.hlsl
    // ========================================================================
    public static string GenerateHlsl()
    {
        var o = new TextOut();
        o.Line("// <auto-generated>");
        o.Line("//   由 tools/AbiGen 生成——不要手改。定义点：src/Contracts/Abi.cs 的静态数据表。");
        o.Line("//   改 ABI 的唯一流程：改 Abi.cs → dotnet run --project tools/AbiGen → 提交生成物。");
        o.Line("//   生成器确定性：无日期、无环境变量、无绝对路径，仅按声明序输出。");
        o.Line("// </auto-generated>");
        o.Line("//");
        o.Line("// 顶点流后端（Unity 段 MeshRenderer 与 WebGL2/GLES3 同一份四角展开）的 ABI include。");
        o.Line("// 整数字段一律 UInt32 顶点属性：float32 顶点流会把 glyphIndex 圆到邻字形（fork 教训）。");
        o.Line();
        o.Line("#ifndef FAIRYNEXT_ABI_G_HLSL");
        o.Line("#define FAIRYNEXT_ABI_G_HLSL");
        o.Line();

        o.Line("// ---- 标量 ----");
        var scalarRows = new List<Row>();
        foreach (var s in Abi.Scalars)
        {
            if ((s.Scope & AbiScope.Hlsl) == 0) continue;
            scalarRows.Add(new Row("#define " + HlslName(s.Name) + " " + ScalarLiteral(s), s.Doc));
        }
        EmitAligned(o, scalarRows);
        o.Line();

        EmitHlslStruct(o, "FnQuadInstance", QuadPrefix, Abi.QuadInstanceFields, Abi.QuadInstanceSize,
            "QuadInstance —— 唯一主路径的可见内容单位");
        EmitHlslStruct(o, "FnClipEntry", ClipPrefix, Abi.ClipEntryFields, Abi.ClipEntrySize,
            "ClipEntry —— 条目 0 = None 哨兵，shader 对其零采样");

        EmitHlslBits(o, RoutePrefix, "route", Abi.RouteBits, "route 位域（QuadInstance.route）");
        EmitHlslBits(o, FlagsPrefix, "flags", Abi.QuadFlagBits, "flags 位域（QuadInstance.flags）");
        EmitHlslBits(o, RadialFillPrefix, "aux", Abi.RadialFillAuxBits,
            "aux 位域（QuadInstance.aux，仅 flags.radialFill 置位时有效）");

        o.Line("#endif // FAIRYNEXT_ABI_G_HLSL");
        return o.ToString();
    }

    // ========================================================================
    // C# 公共体（布局文件与 mock 文件共用——两份文本的差异只有头/命名空间/类名/校验）
    // ========================================================================
    private static void EmitCsBody(TextOut o, bool includeVerify)
    {
        const string I = "    ";

        o.Line(I + "// ---- 标量 ----");
        foreach (var s in Abi.Scalars)
        {
            if ((s.Scope & AbiScope.CSharp) == 0) continue;
            o.Line(I + "/// <summary>" + Xml(s.Doc) + "</summary>");
            o.Line(I + "public const " + (s.Hex ? "uint" : "int") + " " + s.Name + " = " + ScalarLiteral(s) + ";");
        }
        o.Line();

        EmitCsFields(o, I, QuadPrefix, "QuadInstance 字段（80B，16B 对齐）", Abi.QuadInstanceFields);
        EmitCsFields(o, I, ClipPrefix, "ClipEntry 字段（48B）", Abi.ClipEntryFields);
        EmitCsBits(o, I, RoutePrefix, "route", "route 位域", Abi.RouteBits);
        EmitCsBits(o, I, FlagsPrefix, "flags", "flags 位域", Abi.QuadFlagBits);
        EmitCsBits(o, I, RadialFillPrefix, "aux", "aux 位域（仅 flags.radialFill 置位时有效）", Abi.RadialFillAuxBits);
        EmitCsPropIds(o, I);
        EmitCsAsserts(o, I);

        if (includeVerify) EmitCsVerify(o, I);
    }

    private static void EmitCsHeader(TextOut o, string what, string? note = null)
    {
        o.Line("// <auto-generated>");
        o.Line("//   由 tools/AbiGen 生成——不要手改。定义点：src/Contracts/Abi.cs 的静态数据表。");
        o.Line("//   改 ABI 的唯一流程：改 Abi.cs → dotnet run --project tools/AbiGen → 提交生成物。");
        o.Line("//   生成器确定性：无日期、无环境变量、无绝对路径，仅按声明序输出。");
        o.Line("//   本文件：" + what);
        o.Line("// </auto-generated>");
        if (note != null)
        {
            o.Line("//");
            o.Line(note);
        }
        o.Line();
        // <auto-generated> 头会让编译器把本文件视为生成代码：可空上下文默认关闭，
        // 工程级 <Nullable>enable</Nullable> 不再覆盖它（CS8669）。显式开回来。
        o.Line("#nullable enable");
        o.Line();
    }

    private static void EmitCsFields(TextOut o, string indent, string prefix, string title, AbiField[] fields)
    {
        o.Line(indent + "// ---- " + title + " ----");
        foreach (var f in fields)
        {
            o.Line(indent + "/// <summary>" + f.HlslName + " @" + Inv(f.Offset) + " +" + Inv(f.Size)
                + "：" + Xml(f.Doc) + "</summary>");
            o.Line(indent + "public const int " + prefix + f.Name + "Offset = " + Inv(f.Offset) + ";");
            o.Line(indent + "public const int " + prefix + f.Name + "Size = " + Inv(f.Size) + ";");
        }
        o.Line();
    }

    private static void EmitCsBits(TextOut o, string indent, string prefix, string param, string title, AbiBitField[] bits)
    {
        o.Line(indent + "// ---- " + title + "（表覆盖全 32 位；保留位写零）----");
        foreach (var b in bits)
        {
            o.Line(indent + "/// <summary>" + BitRange(b) + "：" + Xml(b.Doc) + "</summary>");
            o.Line(indent + "public const int " + prefix + b.Name + "Shift = " + Inv(b.Shift) + ";");
            o.Line(indent + "public const int " + prefix + b.Name + "Bits = " + Inv(b.Width) + ";");
            o.Line(indent + "public const uint " + prefix + b.Name + "Mask = " + HexMask(b.Width) + ";");
        }
        o.Line();
        o.Line(indent + "// ---- " + title + " 取值（与 HLSL 侧同名宏逐字对应）----");
        foreach (var b in bits)
        {
            o.Line(indent + "/// <summary>取 " + param + "." + LowerFirst(b.Name) + "。</summary>");
            o.Line(indent + "public static uint " + prefix + b.Name + "(uint " + param + ") => ("
                + param + " >> " + prefix + b.Name + "Shift) & " + prefix + b.Name + "Mask;");
        }
        o.Line();
    }

    private static void EmitCsPropIds(TextOut o, string indent)
    {
        o.Line(indent + "// ---- PropId 分组（组间 gap 供 append-only 增长；id 0 = None 哨兵）----");
        foreach (var g in Abi.PropGroups)
        {
            o.Line(indent + "/// <summary>" + Xml(g.Doc) + "</summary>");
            o.Line(indent + "public const byte PropGroup" + g.Name + "First = " + Inv(g.First) + ";");
            o.Line(indent + "public const byte PropGroup" + g.Name + "Last = " + Inv(g.Last) + ";");
        }
        o.Line();
        o.Line(indent + "// ---- PropId（本期启用者；新 id 追加到所属分组末尾，永不重编号）----");
        o.Line(indent + "/// <summary>无属性哨兵。</summary>");
        o.Line(indent + "public const byte PropIdNone = 0;");
        foreach (var p in Abi.PropIds)
        {
            o.Line(indent + "/// <summary>[" + p.Group + "] " + Xml(p.Doc) + "</summary>");
            o.Line(indent + "public const byte PropId" + p.Name + " = " + Inv(p.Id) + ";");
        }
        o.Line();
    }

    /// <summary>
    /// 编译期断言：条件不成立时表达式折叠为 1/0 → CS0020，构建失败（L0：错在跑起来之前）。
    /// 手改生成物里的单个偏移不会安静通过——先撞编译错，再撞字节比对门。
    /// </summary>
    private static void EmitCsAsserts(TextOut o, string indent)
    {
        o.Line(indent + "// ---- 编译期断言：字段首尾相接、末字段收口于结构尺寸、位域覆盖全 32 位 ----");
        o.Line(indent + "// 不成立即 1/0 → CS0020 编译错（L0 门：错误在跑起来之前死掉）。");
        EmitFieldAsserts(o, indent, QuadPrefix, Abi.QuadInstanceFields, "QuadInstanceSize");
        EmitFieldAsserts(o, indent, ClipPrefix, Abi.ClipEntryFields, "ClipEntrySize");
        EmitBitAsserts(o, indent, RoutePrefix, Abi.RouteBits);
        EmitBitAsserts(o, indent, FlagsPrefix, Abi.QuadFlagBits);
        EmitBitAsserts(o, indent, RadialFillPrefix, Abi.RadialFillAuxBits);
        o.Line();
    }

    private static void EmitFieldAsserts(TextOut o, string indent, string prefix, AbiField[] fields, string sizeConst)
    {
        for (int i = 0; i < fields.Length; i++)
        {
            string rhs = i + 1 < fields.Length ? prefix + fields[i + 1].Name + "Offset" : sizeConst;
            o.Line(indent + "private const int Assert" + prefix + fields[i].Name + " = 1 / (("
                + prefix + fields[i].Name + "Offset + " + prefix + fields[i].Name + "Size == " + rhs + ") ? 1 : 0);");
        }
    }

    private static void EmitBitAsserts(TextOut o, string indent, string prefix, AbiBitField[] bits)
    {
        for (int i = 0; i < bits.Length; i++)
        {
            string rhs = i + 1 < bits.Length ? prefix + bits[i + 1].Name + "Shift" : "32";
            o.Line(indent + "private const int Assert" + prefix + bits[i].Name + " = 1 / (("
                + prefix + bits[i].Name + "Shift + " + prefix + bits[i].Name + "Bits == " + rhs + ") ? 1 : 0);");
        }
    }

    /// <summary>
    /// 定义点交叉校验：生成物常量（编译期）vs Abi.cs 数据表（运行期）。逐项比，首条不符即返回说明。
    /// 覆盖字节比对门够不着的一类事故：生成物与定义点被同时手改成「自洽但错」的状态。
    /// </summary>
    private static void EmitCsVerify(TextOut o, string indent)
    {
        const string I2 = "        ";
        o.Line(indent + "/// <summary>");
        o.Line(indent + "/// 定义点交叉校验：本文件常量 vs <see cref=\"Abi\"/> 数据表。null = 一致；");
        o.Line(indent + "/// 非 null = 首条不符的说明。表长变化亦在此暴露（生成物按当时表长展开）。");
        o.Line(indent + "/// </summary>");
        o.Line(indent + "public static string? Verify()");
        o.Line(indent + "{");

        o.Line(I2 + "if (Abi.Scalars.Length != " + Inv(Abi.Scalars.Length) + ") return \"Abi.Scalars 表长与生成物不符\";");
        for (int i = 0; i < Abi.Scalars.Length; i++)
        {
            var s = Abi.Scalars[i];
            if ((s.Scope & AbiScope.CSharp) == 0) continue;
            o.Line(I2 + "if (Abi.Scalars[" + Inv(i) + "].Value != " + s.Name + ") return \"标量 " + s.Name + " 与生成物不符\";");
        }

        EmitVerifyFields(o, I2, QuadPrefix, "Abi.QuadInstanceFields", Abi.QuadInstanceFields);
        EmitVerifyFields(o, I2, ClipPrefix, "Abi.ClipEntryFields", Abi.ClipEntryFields);
        EmitVerifyBits(o, I2, RoutePrefix, "Abi.RouteBits", Abi.RouteBits);
        EmitVerifyBits(o, I2, FlagsPrefix, "Abi.QuadFlagBits", Abi.QuadFlagBits);
        EmitVerifyBits(o, I2, RadialFillPrefix, "Abi.RadialFillAuxBits", Abi.RadialFillAuxBits);

        o.Line(I2 + "if (Abi.PropGroups.Length != " + Inv(Abi.PropGroups.Length) + ") return \"Abi.PropGroups 表长与生成物不符\";");
        for (int i = 0; i < Abi.PropGroups.Length; i++)
        {
            var g = Abi.PropGroups[i];
            o.Line(I2 + "if (Abi.PropGroups[" + Inv(i) + "].First != PropGroup" + g.Name + "First"
                + " || Abi.PropGroups[" + Inv(i) + "].Last != PropGroup" + g.Name + "Last) return \"分组 " + g.Name + " 区间与生成物不符\";");
        }
        o.Line(I2 + "if (Abi.PropIds.Length != " + Inv(Abi.PropIds.Length) + ") return \"Abi.PropIds 表长与生成物不符\";");
        for (int i = 0; i < Abi.PropIds.Length; i++)
        {
            var p = Abi.PropIds[i];
            o.Line(I2 + "if (Abi.PropIds[" + Inv(i) + "].Id != PropId" + p.Name + ") return \"PropId " + p.Name + " 与生成物不符\";");
        }

        o.Line(I2 + "return null;");
        o.Line(indent + "}");
    }

    private static void EmitVerifyFields(TextOut o, string indent, string prefix, string table, AbiField[] fields)
    {
        o.Line(indent + "if (" + table + ".Length != " + Inv(fields.Length) + ") return \"" + table + " 表长与生成物不符\";");
        for (int i = 0; i < fields.Length; i++)
        {
            o.Line(indent + "if (" + table + "[" + Inv(i) + "].Offset != " + prefix + fields[i].Name + "Offset"
                + " || " + table + "[" + Inv(i) + "].Size != " + prefix + fields[i].Name + "Size) return \""
                + prefix + fields[i].Name + " 偏移/大小与生成物不符\";");
        }
    }

    private static void EmitVerifyBits(TextOut o, string indent, string prefix, string table, AbiBitField[] bits)
    {
        o.Line(indent + "if (" + table + ".Length != " + Inv(bits.Length) + ") return \"" + table + " 表长与生成物不符\";");
        for (int i = 0; i < bits.Length; i++)
        {
            o.Line(indent + "if (" + table + "[" + Inv(i) + "].Shift != " + prefix + bits[i].Name + "Shift"
                + " || " + table + "[" + Inv(i) + "].Width != " + prefix + bits[i].Name + "Bits) return \""
                + prefix + bits[i].Name + " 位域与生成物不符\";");
        }
    }

    // ========================================================================
    // HLSL 片段
    // ========================================================================
    private static void EmitHlslStruct(TextOut o, string structName, string prefix, AbiField[] fields, int totalSize, string title)
    {
        o.Line("// ---- " + title + "（" + Inv(totalSize) + "B）----");
        o.Line("struct " + structName);
        o.Line("{");
        int offsetWidth = 0, sizeWidth = 0;
        foreach (var f in fields)
        {
            if (Inv(f.Offset).Length > offsetWidth) offsetWidth = Inv(f.Offset).Length;
            if (Inv(f.Size).Length > sizeWidth) sizeWidth = Inv(f.Size).Length;
        }
        var members = new List<Row>();
        foreach (var f in fields)
        {
            members.Add(new Row("    " + PadRight(HlslType(f.Kind), 7) + f.HlslName + ";",
                "@" + PadLeft(Inv(f.Offset), offsetWidth) + " +" + PadLeft(Inv(f.Size), sizeWidth) + "  " + f.Doc));
        }
        EmitAligned(o, members);
        o.Line("};");
        foreach (var f in fields)
        {
            string root = HlslName(prefix + f.Name);
            o.Line("#define " + root + "_OFFSET " + Inv(f.Offset));
            o.Line("#define " + root + "_SIZE " + Inv(f.Size));
        }
        o.Line();
    }

    private static void EmitHlslBits(TextOut o, string prefix, string param, AbiBitField[] bits, string title)
    {
        o.Line("// ---- " + title + "，表覆盖全 32 位；保留位写零 ----");
        var rows = new List<Row>();
        foreach (var b in bits)
        {
            string root = HlslName(prefix + b.Name);
            rows.Add(new Row("#define " + root + "_SHIFT " + Inv(b.Shift), BitRange(b) + "  " + b.Doc));
            rows.Add(new Row("#define " + root + "_BITS " + Inv(b.Width), null));
            rows.Add(new Row("#define " + root + "_MASK " + HexMask(b.Width), null));
            rows.Add(new Row("#define " + root + "(" + param + ") (((" + param + ") >> " + root + "_SHIFT) & " + root + "_MASK)", null));
        }
        EmitAligned(o, rows);
        o.Line();
    }

    // ========================================================================
    // 格式化工具（全部 InvariantCulture——生成物字节不得随机器区域设置变化）
    // ========================================================================
    private static string Inv(long v) => v.ToString(CultureInfo.InvariantCulture);

    /// <summary>"b5" / "b8-15"——位域的人类可读区间。</summary>
    private static string BitRange(AbiBitField b) =>
        "b" + Inv(b.Shift) + (b.Width > 1 ? "-" + Inv(b.Shift + b.Width - 1) : string.Empty);

    /// <summary>一行输出：代码 + 可选行尾注释。注释列按本段内**带注释行**的最大宽度对齐。</summary>
    private readonly struct Row
    {
        public readonly string Code;
        public readonly string? Comment;

        public Row(string code, string? comment)
        {
            Code = code;
            Comment = comment;
        }
    }

    private static void EmitAligned(TextOut o, List<Row> rows)
    {
        int width = 0;
        foreach (Row r in rows)
        {
            if (r.Comment != null && r.Code.Length > width) width = r.Code.Length;
        }
        foreach (Row r in rows)
        {
            o.Line(r.Comment == null ? r.Code : PadRight(r.Code, width) + "  // " + r.Comment);
        }
    }

    /// <summary>
    /// 标量字面量。C# 与 HLSL 今天恰好同形（两边都收 0xFFFFFFFFu 与十进制），故共用一份；
    /// 哪天两侧字面量语法分岔，在此处分叉，而不是在调用点各写各的。
    /// </summary>
    private static string ScalarLiteral(AbiScalar s) =>
        s.Hex ? "0x" + s.Value.ToString("X8", CultureInfo.InvariantCulture) + "u" : Inv(s.Value);

    private static string HexMask(int width)
    {
        uint mask = width >= 32 ? uint.MaxValue : (1u << width) - 1u;
        return "0x" + mask.ToString("X", CultureInfo.InvariantCulture) + "u";
    }

    private static string HlslType(AbiFieldKind kind) => kind switch
    {
        AbiFieldKind.Float4 => "float4",
        AbiFieldKind.Float2 => "float2",
        AbiFieldKind.UInt32 => "uint",
        _ => "uint",
    };

    /// <summary>PascalCase → FN_UPPER_SNAKE（下划线插在「小写/数字 之后的大写」前）。</summary>
    private static string HlslName(string pascal)
    {
        var sb = new StringBuilder("FN_");
        for (int i = 0; i < pascal.Length; i++)
        {
            char c = pascal[i];
            if (i > 0 && char.IsUpper(c) && !char.IsUpper(pascal[i - 1])) sb.Append('_');
            sb.Append(char.ToUpperInvariant(c));
        }
        return sb.ToString();
    }

    private static string LowerFirst(string s) => char.ToLowerInvariant(s[0]) + s.Substring(1);

    private static string PadRight(string s, int width) => s.Length >= width ? s : s + new string(' ', width - s.Length);

    private static string PadLeft(string s, int width) => s.Length >= width ? s : new string(' ', width - s.Length) + s;

    /// <summary>XML doc 转义——文档串里出现 &amp;/&lt;/&gt; 时不许把生成的 C# 编译警告成错误。</summary>
    private static string Xml(string s) => s.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");

    /// <summary>只会 '\n' 的行写入器：生成物行尾不随宿主平台变化（Windows 上重生成必须同字节）。</summary>
    private sealed class TextOut
    {
        private readonly StringBuilder _sb = new StringBuilder();

        public void Line() => _sb.Append('\n');

        public void Line(string text)
        {
            _sb.Append(text);
            _sb.Append('\n');
        }

        public override string ToString() => _sb.ToString();
    }
}
